### ISSUE TITLE
 Get-Issuedrequest Returns wrong value

### ISSUE THREAD

**Issue by Zipties** [PKISolutions/PSPKI#100]
Hello, I followed the documentation here to assist me in creating a script to revoke employee certificates during off boarding.
https://www.pkisolutions.com/tools/pspki/Revoke-Certificate/

When using the example for disabling a user in the "users" OU I consistently return a value for a user who has nothing to do with the query, no matter what the query is. 

![image](https://user-images.githubusercontent.com/11506166/78712123-b9e32c80-78dd-11ea-8516-109935c5c199.png)

**Comment by Crypt32** [comment]
Can you elaborate? `-gt`, `-ge`, `-lt` and `-le` are tricky for string values. The behavior is explained a bit in my blog post: https://www.sysadmins.lv/blog-en/string-comparison-in-certification-authority-database-queries.aspx

What is the common name for this particular user?
