### ISSUE TITLE
OCSPRequest constuctor unable to cast boolean for NONCE

### ISSUE THREAD

**Issue by DarcSparc** [PKISolutions/PSPKI#101]
Uncertain if I am missing newer instructions, or there is a bug with the updated version.  Trying to perform some testing of OCSP NONCE and running into issues.  Here is the error output.

New-Object : Cannot convert argument "1", with value: "True", for "OCSPRequest" to type "System.Security.Cryptography.X509Certificates.X509Certificate2": "Cannot convert value "True" to type
"System.Security.Cryptography.X509Certificates.X509Certificate2". Error: "Invalid cast from 'System.Boolean' to 'System.Security.Cryptography.X509Certificates.X509Certificate2'.""
At line:1 char:12
+ $request = New-Object pki.ocsp.ocsprequest $cert,$true
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

**Comment by Crypt32** [comment]
This constructor is deprecated. Instead, pass only certificate object to New-Object command and then set nonce via property:

```
$req = new-object pki.ocsp.ocsprequest $cert
$req.Nonce = $true
...
```

**Comment by DarcSparc** [comment]
That makes sense.  I clearly missed that the constructor was deprecated in reading through the notes and documentation.  Thank you for the fast response on this.

I also confirmed $response = $request.SendRequest("POST") successfully resolves the "malformedrequest" error that was posted previously.
