### ISSUE TITLE
New-SelfSignedCertificateEx fails to use ECDSA on Microsoft Smart Card KSP

### ISSUE THREAD

**Issue by cdanger** [PKISolutions/PSPKI#102]
I am trying to generate a self-signed certificate with ECDSA key pair on a smartcard by running this New-SelfSignedCertificateEx command on my Windows 10 machine:

```powershell
New-SelfSignedCertificateEx -Subject "CN=John D" -AlgorithmName ECDSA_P256 -KeyLength 256 -ProviderName "Microsoft Smart Card Key Storage Provider"
```
I get this unexpected error:
```powershell
New-SelfSignedCertificateEx : Exception calling "Build" with "1" argument(s): "This smart card does not support the
requested feature. (Exception from HRESULT: 0x80100022)"
At line:1 char:1
+ New-SelfSignedCertificateEx -Subject "CN=John D" -AlgorithmName ECDSA ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SelfSignedCertificateEx], MethodInvocationException
    + FullyQualifiedErrorId : COMException,New-SelfSignedCertificateEx
```

I say *unexpected* because the "Microsoft Smart Card Key Storage Provider" supports ECDSA P256 according to this command:

```powershell
> certutil -csptest -user -csp SC | Select-String ECDSA_P256

   ECDSA_P256
   ECDSA_P256
    NCryptCreatePersistedKey(Microsoft Smart Card Key Storage Provider, ECDSA_P256)
  Algorithm Name: ECDSA_P256
   ECDSA_P256
    ECDSA_P256
    ECDSA_P256
    ECDSA_P256
```

Could you tell what I am missing?

**Comment by Crypt32** [comment]
Have you tried to specify your smart card vendor KSP instead of Microsoft one?

**Comment by cdanger** [comment]
Actually, I am using Windows-10-native [Virtual Smart Cards](https://docs.microsoft.com/en-us/windows/security/identity-protection/virtual-smart-cards/virtual-smart-card-get-started), so Microsoft is the vendor I guess.

**Comment by Crypt32** [comment]
Have you tried this provider: Microsoft Platform Crypto Provider?

Unlike software KSP, Microsoft Smart Card Key Storage Provider is abstract provider and has no default implementation. On a system, you can use this provider to query from all providers that implement from Microsoft Smard Card KSP, but when writing, you have to specify particular Microsoft Smart Card KSP implementation.

For TPM you must use "Microsoft Platform Crypto Provider" provider when generating keys. When reading, you can use "Microsoft Platform Crypto Provider" to query only this provider, or "Microsoft Smart Card Key Storage Provider", which will query all providers that implement it.

**Comment by cdanger** [comment]
Thanks for the tip. However, when I use "Microsoft Platform Crypto Provider" instead, the self-signed (and keypair) is generated *without asking for the PIN* that I set on the Virtual Smartcard (with tpmvscmgr command), which makes me think it is not using the virtual smartcard interface to do that.
For comparison, if I use "Microsoft Smart Card Key Storage Provider" but with RSA, the command works just fine and asks for the PIN:
```powershell
New-SelfSignedCertificateEx -Subject "CN=John D" -AlgorithmName RSA -KeyLength 2048 -ProviderName "Microsoft Smart Card Key Storage Provider"
```

So let's say I want to use "Microsoft Platform Crypto Provider" anyway, how do I set a PIN with New-SelfSignedCertificateEx" to protect the generated keys ?

**Comment by Crypt32** [comment]
I've tried the `Microsoft Platform Crypto Provider` provider and indeed it writes to TPM and accessible from `Microsoft Smart Card Key Storage Provider`.

**Comment by cdanger** [comment]
OK, so let's forget about the "Microsoft Smart card KSP" and "Virtual smartcard" for now, seems to be a dead end. 
Now, if I use **New-SelfSignedCertificateEx with "Microsoft Platform Crypto Provider"**, how do you set the  **PIN/password for key protection** with this command? or make it prompt to enter the PIN?

**Comment by joeri-juramento** [comment]
You could add the switch `-KeyProtection ProtectHigh`. ([Source](https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps#parameters#SearchFor%22ProtectHigh%22))

It would prompt for a password/pin when you interact with the certificate, some caching applies though, after that. (Adding this switch only makes sense for software-based-certs as far as I know.)

However, it would not provide you with the same level of protection if the certificate was saved inside the Virtual Smart Card on the TPM. From my understanding using **Microsoft Platform Crypto Provider** will use the TPM as a certificate generator, but the output is in the Windows certificate store, not the TPM. (Verified with command `certutil -scinfo`)

### ECDSA Cert generated on TPM but saved in cert store:
For example, the following set-up for a signing cert will result in a cert in user certificate store, generated* by the TPM. The private key is present** in the store, but cannot be exported**.

```
New-SelfSignedCertificate -Type Custom -Subject "CN=Testing-Cert2" `
-TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3","2.5.29.17={text}upn=Testing-cert2@TPM.MACHINENAME") `
-KeyUsage DigitalSignature -KeyAlgorithm ECDSA_P256 -HashAlgorithm sha256 `
-CurveExport CurveName -CertStoreLocation "Cert:\CurrentUser\My" -NotAfter (Get-Date).AddDays(5) `
-Provider "Microsoft Platform Crypto Provider" -KeyProtection ProtectHigh
```
### ECDSA Cert generated on and saved inside Virtual Smart Card:
What I was actually trying to achieve, simular to you, is generating it and saving it on the Virtual Smart Card / TPM, with **Microsoft Smart Card Key Storage Provider**:
```
New-SelfSignedCertificate -Type Custom -Subject "CN=Testing-Cert1" `
-TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3","2.5.29.17={text}upn=Testing-cert2@TPM.MACHINENAME") `
-KeyUsage DigitalSignature -KeyAlgorithm ECDSA_P256 -HashAlgorithm sha256 `
-CurveExport CurveName -CertStoreLocation "Cert:\CurrentUser\My" -NotAfter (Get-Date).AddDays(5) `
-Provider "Microsoft Smart Card Key Storage Provider"

```
⬆This unfortunatly does not work, I encounter the same error as you.
And like you experienced, RSA is not a problem: ⬇
### RSA Cert generated on and saved inside Virtual Smart Card:
```
New-SelfSignedCertificate -Type CodeSigningCert -Subject "CN=Testing-Cert3" `
-TextExtension @("2.5.29.17={text}upn=Testing-cert3@TPM.MACHINENAME") `
-KeyUsage DigitalSignature -KeyAlgorithm RSA -KeyLength 2048 -HashAlgorithm sha256 `
-CurveExport CurveName -CertStoreLocation "Cert:\CurrentUser\My" `
-NotAfter (Get-Date).AddDays(5) `
-Provider "Microsoft Smart Card Key Storage Provider"
```

This results in a certificate on/in my Virtual Smart Card which I can verify with `certutil -scinfo` and clean up with 
`certutil -delkey -csp “Microsoft Smart Card Key Storage Provider” “{key-container-id}” `

### Back to Virtual Smart Card:
Anyone any idea how to get ECC certs on the Virtual Smart Card is most welcome to speak up.

[Why I/we think it should work.](https://docs.microsoft.com/en-us/windows/win32/seccertenroll/cng-key-storage-providers)

I keep re-reading @Crypt32's remark:

> Unlike software KSP, Microsoft Smart Card Key Storage Provider is abstract provider and has no default implementation. On a system, you can use this provider to query from all providers that implement from Microsoft Smard Card KSP, but when writing, you have to specify particular Microsoft Smart Card KSP implementation.

I wonder if there is a different provider besides the tested ones we have to address when generating ECC certs. However, when generating ECC certs on the TPM, but not saving in the Smart Card, it works, so it remains a mystery to me why this is not working in the first place.

\* assumed
** validated by testing
