### ISSUE TITLE
Painfully slow (impossible) pspki operations on CA with millions of certificates

### ISSUE THREAD

**Issue by mfelicien** [PKISolutions/PSPKI#103]
having a hard time using any PSPKI cmdlet with CA's (Enterprise) which have over 2 millions certificates.. Tryging something easy as get-issuedrequest -filter requestId -gt xxxx takes forever ,ive waited over an hour and it still didnt return even when setting or querying one record. 

trying the same with other CA with smaller databases work well. 

Certuil however, in both of this cases work like a champ. Baring me having to re-write hundreds of lines of codes to use certutil install of pspki. any ideas here

were using both 3.4 and 3.5 issues are the same.

**Comment by Crypt32** [comment]
Have you tried to specify `-Page` and `-PageSize` parameters to limit the output size and see if it helps?

**Comment by mfelicien** [comment]
Yep, ive treid page and page size. Eveb with a page size of 10 it takes forever on large database. I used requestid -gt xxxx  -pagesize 10 and it was 15 minutes and hadnt come back yet :(

**Comment by Crypt32** [comment]
how much time it takes to get result when you specify specific RequestID?

**Comment by mfelicien** [comment]
45 Minutes. Any command to the CA's with large databases take quite as long.. even Get-CertificationAuthority. It all used to work well but as the databases grew, it started taking more and more time. 
 
measure-command { Get-IssuedRequest -CertificationAuthority <removed> -Filter "RequestID -eq 2696024" }


Days              : 0
Hours             : 0
Minutes           : 45
Seconds           : 14

**Comment by Crypt32** [comment]
> Get-CertificationAuthority

it has nothing to do with CA size. Only DB queries are affected by DB size. I'm going to investigate this.

**Comment by mfelicien** [comment]
How can I help?  Is there any data I can get you to help narrow it down?

**Comment by Crypt32** [comment]
not much at this moment. Filtering by ID should be fast enough, because this column is indexed and filter should leverage the performance boost when looking for requested row. And must be a matter of seconds, not 45 minutes.

**Comment by PatrickOnGit** [comment]
@mfelicien  
just out of curiosity:
can you share your server specs?
how many entries do your CAs have? 
are there any esent errors in system/application log?
is searching using certutil behaving different?

we run a CA with over 20mio entries and queries take some time. but not 45 minutes.

best regards
Patrick

**Comment by compnetsys** [comment]
Hey there @PatrickOnGit , thanks for reaching out. I took the time to validate that the issue still persisted. Here are the specs
16GB RAM
4 vCPU

I took the time to profile the CPU usage and for about the frist 10 seconds it hits about 90% then back to about 25%. 
Certutil is still able to return the results in seconds. 

Currently, the CA has about 2.6 Million certs in its store. Also no esent errors in the application log

**Comment by Crypt32** [comment]
What is the size of DB log files?

**Comment by compnetsys** [comment]
Currently 365 1mb log files.

**Comment by PatrickOnGit** [comment]
what happens if you use the parameter -RequestID instead of -filter?

**Comment by KevOtt** [comment]
Just going to resurrect this issue and add some context, working on version 3.5 of PSPKI.

The issue appears to be with the Get-CertificationAuthority cmdlet, it looks like this cmdlet queries the entire content of the baseCRL and deltaCRL for each CA; in the case where there are many thousands of entries in the CRL this cmdlet is extremely slow, in the case of one of our CAs it's minutes of run time as it pulling multiple megabytes down from the CA.

It appears that running a cmdlet such as Get-IssuedRequest without piping in the CertificateAuthority object, the cmdlet will call Get-CertificationAuthority on each execution, which again can result in minutes worth of waiting while it queries the CRLs.  

I'm not sure if this is intended functionality or not, but adding an option to skip querying the CRL or adding some other way to handle the CRL would solve this issue.

**Comment by Crypt32** [comment]
> it looks like this cmdlet queries the entire content of the baseCRL and deltaCRL for each CA; in the case where there are many thousands of entries in the CRL this cmdlet is extremely slow

yes, it was the case in the past. Even though I'm using very robust ASN parser, it still takes a lot of time to parse large CRLs. In fact, this was fixed in 3.7 version: https://github.com/PKISolutions/pkix.net/blob/c8a0a1abdabad9ba2bf9fc58af4de65d29cf58e9/PKI/CertificateServices/CertificateAuthority.cs#L165
you see that `BaseCRL` and `DeltaCRL` properties are marked obsolete. Since 3.7, when you build `CertificationAuthority` object, it no longer read and parse CRLs unless corresponding method is invoked. And in 3.7. I completely re-wrote the code how we discover and build CA object and a lot of related code was re-written from scratch. Just update PSPKI to latest version.

**Comment by compnetsys** [comment]
Awesome thanks you @Crypt32 . @KevOtt  Lets test the latest version  and see if this works better

**Comment by Crypt32** [comment]
Hey guys, any update?
