### ISSUE TITLE
Problem with Certificate Templates

### ISSUE THREAD

**Issue by itsvivs** [PKISolutions/PSPKI#106]
When running below command, not all the certificates getting in the list, due to few certificate template names showing OIDs instead of Displayname - 

Get-CertificationAuthority <Certficate authority server> |Get-IssuedRequest -Filter "NotAfter -ge $(Get-Date)", "NotAfter -le $((Get-Date).AddMonths(2))"|Where{((Get-CertificateTemplate -displayname $_.Certificatetemplate).autoenrollmentallowed) -ne "True"}

**Comment by Crypt32** [comment]
It is expected. CA database stores only template common name (V1 templates) or template OID (V2+ templates). CA do not store template display name. Thus, you have to do some additional work: determine if `CertificateTemplate` property on DB row stores OID (something like 1.3.6.1.4.1.311.21...) or alphanumerical characters (`Machine`, `User`, `EFS`).

If DB row returns OID, then you must attempt to translate this OID to display name by calling:
```
$oid = Get-ObjectIdentifier $row.CertificateTemplate
```
and then evaluate `FriendlyName` property on return value. If it is non-empty, then call `Get-CertificateTemplate -display $oid.FriendlyName`. If Firendly Name is null/empty, then there is no such template (maybe deleted).

If outout contains string characters, then query for template by calling `Get-CertificateTemplate -Name $row.CertificateTemplate`. There is no other way to solve this puzzle.
