### ISSUE TITLE
Breaking change

### ISSUE THREAD

**Issue by JAK1047** [PKISolutions/PSPKI#111]
#51 has become a breaking change for me.

PS C:\Users\e0172010> Import-Module PSPKI
$WinRootCACertPath = '\\cwwapp915\CertEnroll\WIN-Root-CA.crl'

$WinRootCA = (Get-CertificateRevocationList -Path $WinRootCACertPath).NextUpdate
New-Object : Exception calling ".ctor" with "1" argument(s): "The given path's format is not supported."
At C:\Program Files\WindowsPowerShell\Modules\PSPKI\3.7.1\Client\Get-CertificateRevocationList.ps1:20 char:4

The path property on Resolve-Path gives a Path object. You want ProviderPath:

PS C:\Users\e0172010> (Resolve-Path $Path).ProviderPath
\\cwwapp915\CertEnroll\WIN-Root-CA.crl

PS C:\Users\e0172010> (Resolve-Path $Path).Path
Microsoft.PowerShell.Core\FileSystem::\\cwwapp915\CertEnroll\WIN-Root-CA.crl

Swapping the cmdlet fixes it or just removing the typing information from the string if it exists (Resolve-Path $Path).Path.Replace('Microsoft.PowerShell.Core\FileSystem::','')

**Comment by Crypt32** [comment]
Are you running PowerShell Core? I don't see this behavior in Windows PowerShell 5.1. It seems, it is only PS Core-specific issue.

**Comment by JAK1047** [comment]
Nope 5.1. Microsoft.Powershell.Core isn't related to Powershell Core\6 it's the builtin module that contains a lot of Powershell features https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/?view=powershell-5.1

PS C:\Users\e0172010> $PSVersionTable.PSVersion
(Resolve-Path '\\cwwapp1726\D$\dumpfile.dmp').Path


Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14409  1018    
Microsoft.PowerShell.Core\FileSystem::\\cwwapp1726\D$\dumpfile.dmp

Resolve-Path returns a System.Management.Automation.PathInfo typed object when not using the -Relative switch. So if you point it to say an AdminShare path like in the example you'll get a provider qualified path: Provider-qualified: FileSystem::c:\temp\foo.txt

Resolve-Path '\\cwwapp1726\D$\dumpfile.dmp' | fl

Drive        : 
Provider     : Microsoft.PowerShell.Core\FileSystem
ProviderPath : \\cwwapp1726\D$\dumpfile.dmp
Path         : Microsoft.PowerShell.Core\FileSystem::\\cwwapp1726\D$\dumpfile.dmp

If you're only trying it with a local file it wouldn't matter:

Resolve-Path 'C:\MasterExcludeList.txt' | fl

Drive        : C
Provider     : Microsoft.PowerShell.Core\FileSystem
ProviderPath : C:\MasterExcludeList.txt
Path         : C:\MasterExcludeList.txt

**Comment by JAK1047** [comment]
You can also covert the provider path if you don't want to expand the ProviderPath propety.

$ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath((Resolve-Path '\\cwwapp1726\D$\dumpfile.dmp').path)

Convert-Path (Resolve-Path '\\cwwapp1726\D$\dumpfile.dmp').path

\\cwwapp1726\D$\dumpfile.dmp
\\cwwapp1726\D$\dumpfile.dmp

**Comment by Crypt32** [comment]
I confirm this bug when using UNC paths. Though, works ok with local paths. I will see what else I can do here and today-tomorrow push an update to PS Gallery as 3.7.2

**Comment by Crypt32** [comment]
Updated in v3.7.2: https://www.powershellgallery.com/packages/PSPKI/3.7.2
