### ISSUE TITLE
Get-CertificationAuthority Exception

### ISSUE THREAD

**Issue by lopez1de** [PKISolutions/PSPKI#114]
Used version 3.4.1.0 without problems. Updated to version 3.7.2 and now get this exception.

```
PS C:\Users\xxx\ > Get-CertificationAuthority -Name "myPKI"
 
New-Object : Cannot find type [SysadminsLV.PKI.Dcom.Implementations.CertConfigD]: verify that the assembly containing this type is loaded.
At C:\Users\xxx\Documents\GitHub\ADhousekeeping\adcs\PSPKI-v3.7.2\Server\Get-CertificationAuthority.ps1:24 char:19
+ ... ertConfig = New-Object SysadminsLV.PKI.Dcom.Implementations.CertConfi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
You cannot call a method on a null-valued expression.
At C:\Users\xxx\Documents\GitHub\ADhousekeeping\adcs\PSPKI-v3.7.2\Server\Get-CertificationAuthority.ps1:25 char:5
+     $CertSrvList = $CertConfig.EnumConfigEntries()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

**Comment by Crypt32** [comment]
What version of SysadminsLV.PKI.dll file is installed in library folder? Show Details tab dialog of file properties.

**Comment by lopez1de** [comment]
![pspkiscreenshot](https://user-images.githubusercontent.com/3635914/91158815-80159580-e6c7-11ea-8f57-b15034079f5b.PNG)

**Comment by Crypt32** [comment]
This library should work. Make sure if you don't have any other instances of PSPKI module installed on a system. I suspect that for some unknown reason, PowerShell loads older version of PKI library.

**Comment by lopez1de** [comment]
Sorry for wasting your time. Indeed I found a copy of PSPKI at `C:\Program Files\WindowsPowerShell\Modules`, which is the correct location. Deleted the folder and got a new copy with `Install-Module PSPKI`

**Comment by Crypt32** [comment]
I'm glad you were able to sort this out!
