### ISSUE TITLE
Question about Get-CertificateTemplate Settings

### ISSUE THREAD

**Issue by NickyGr** [PKISolutions/PSPKI#120]
Dear PSPKI team,
i want to export all settings in a Certificate Template for reporting purposes.
For this i'm using this command in a foreach-object loop:

Get-CertificateTemplate -DisplayName $($_.Displayname) | Select-Object -ExpandProperty Settings

However i don't receive all settings from the template.
example.1: I could not find a way to display the settings from the Compatibility Tab in the Certificate Template.
example.2: How can i display what extension is set as critical and settings in the rest of Key Usage settings?

Maybe there is another way to get these and i'm not aware of yet. 
Any advice is welcome.

**Comment by Crypt32** [comment]
> I could not find a way to display the settings from the Compatibility Tab in the Certificate Template.

it is not a setting of certificate template. It is a part of Certificate Templates MMC snap-in.

> How can i display what extension is set as critical and settings in the rest of Key Usage settings?

you can get this from `Extensions` property of settings:

```PowerShell
$t = Get-CertificateTemplate -Name MyTemplate
$t.Settings.Extensions
```
this will return a list of extensions. Each extension has `Critical` property. You can call `.Format($true)` method for every extension to get extension configuration.

**Comment by NickyGr** [comment]
That did the trick.
Thank you very much for quick response.
