### ISSUE TITLE
Error exception not handled, Get-RequestRow being called from Get-Issued Request

### ISSUE THREAD

**Issue by hmiller10** [PKISolutions/PSPKI#121]
Module version: 3.7.2
CA - Windows Server 2012 R2, with latest patches.

When I attempt to run the below code, I get the error exception at the bottom of this message.

$certProps = @("Request.RequesterName", "CommonName", "ConfigString", "NotBefore", "NotAfter", "SerialNumber", "CertificateTemplate")
$CA = myCA.myDomain.com
$usRequests = @()
try
{
  Write-Verbose -Message "Working on search of $CA" -Verbose
  Connect-CertificationAuthority -ComputerName $CA
                                                
  $usRequests += Get-CertificationAuthority -ComputerName $CA -ErrorAction Stop | Get-IssuedRequest -Property $certProps - 
  Filter "NotAfter -ge $(Get-Date)", "Request.RequesterName -ge 'US\'", "Request.RequesterName -le 'ZA\'" -PageSize 10000000 - 
  ErrorAction Continue | Select-Object -Property $certProps | Sort-Object -Property NotBefore
                                                
  $CA = $null
}
catch
{
                $errorMessage = "{0}: {1}" -f $Error[0], $Error[0].InvocationInfo.PositionMessage
                Write-Error $errorMessage -ErrorAction Continue
}

An error occurred while enumerating through a collection: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE)).: At C:\Program 
Files\WindowsPowerShell\Modules\pspki\3.7.2\Server\Get-RequestRow.ps1:52 char:9
+         $Reader.GetView($skip, $PageSize) | ForEach-Object {
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At line:1 char:1
+ .\Get-USMFIssuedCerts-WIP.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException

I have played around with different try/catch statements and have adjusted the pagesize up and down.

The array variable does indeed have values written to it. However when the error is thrown the script stops. Please help clear this error.

**Comment by Crypt32** [comment]
Reduce page size to something like 10k-50k. When you open connection to CA database we receive a handle which is valid for 10min by default. If data reading exceeds 10mins, CA forcibly closes the connection with `0x80070006: The handle is invalid` exception. By reducing page size to 10-50k entries you can finish page query within this time slot. Then increment page number and read next portion of database data.

Exact page size can be inferred from `$usRequests` entry count. Make page size a bit less (10%) that the number of entries in `$usRequests` variable.

**Comment by hmiller10** [comment]
Reducing the page size did get rid of the connection time out error. This does beg the question of how, with large databases and millions and millions of rows, how can one parse a database like that using PowerShell if the connection is severed.

**Comment by Crypt32** [comment]
You put the call into a loop and iterate over pages until last page returns less rows than page size. Unfortunately, ADCS API don't provide a SQL-like `Count()` function to get the total number of rows, so you need to handle it with returned row count.

**Comment by hmiller10** [comment]
Could you provide me with a code snippet that shows a loop checking the page size. 

Heather
Sent from my iPhone
Please excuse any typos or grammatical errors

**Comment by Crypt32** [comment]
Something like this:

```PowerShell
$ca = Get-CA ca01
$PageSize = 10000
$Page = 1
$i = 0
do {
    $CA | Get-IssuedRequest <YourParameters> -Page $Page -PageSize $PageSize | %{
        $i++
        # do what you need with returned row in $_ variable
    }
    $Page++
} while ($i -eq $PageSize)
```
