### ISSUE TITLE
Start-PsFCIV not detecting new files

### ISSUE THREAD

**Issue by brentil** [PKISolutions/PSPKI#124]
Windows 10 64bit Enterprise 2004
PowerShell 5.1.19041
PowerShell run as admin

I did an initial scan of a folder and built the XML DB.  I had 5 files and they all got added.
```
. .\Start-PsFCIV.ps1
Start-PsFCIV -Path D:\Downloads\FIM\Test -Include * -XML "D:\Downloads\FIM\DB.XML" -HashAlgorithm SHA256 -Recurse -Debug
```
-----------------------------------
Total files processed: 5
Total new added files: 5
Total good files: 0
Total bad files: 0
Total unknown status files: 0
Total missing files: 0
Total locked files: 0
-----------------------------------

I then modified 1 file and added a new file to this folder.  I ran it again and it detected the changed file but the new file was not detected as a deviation from the baseline.

```
Start-PsFCIV -Path D:\Downloads\FIM\Test -Include * -XML "D:\Downloads\FIM\DB.XML" -HashAlgorithm SHA256 -Recurse -Debug
```

-----------------------------------
Total files processed: 5
Total new added files: 0
Total good files: 4
Total bad files: 1
Total unknown status files: 0
Total missing files: 0
Total locked files: 0
-----------------------------------

I tested adding 10 more files to the folder and the same behavior, there's no detection of the new files in the scan.

I also tried passing -Show New and it's just an empty output table.

**Comment by Crypt32** [comment]
This is expected behavior. The intent was to work with static DB file ignoring stuff not included in DB, thus allowing you to have dynamic (and not relevant to integrity check) content in folder. To resolve this, there is `-Rebuild` switch, which checks for **\*new\*** and **\*retired\*** files and updates DB file with actual state of the folder. Be aware that `-Rebuild` switch doesn't perform checksum verification, it only searches for new files that doesn't exist in XML DB and missing files that no longer exist in a folder.

**Comment by brentil** [comment]
I understand now.  How do you build a new baseline then?  Meaning not just the new and deleted files -Rebuild detects but the files who's hashes have changed you want to become the new baseline to check against.  From reading the documentation the only option would be to delete the XML DB and start fresh then since -Rebuild doesn't get those types of changes into a completely fresh baseline?

**Comment by Crypt32** [comment]
> From reading the documentation the only option would be to delete the XML DB and start fresh then since -Rebuild doesn't get those types of changes into a completely fresh baseline?

exactly. Or start in new DB file, same thing.

**Comment by brentil** [comment]
Thanks, I'll close this ticket.
