### ISSUE TITLE
Base 64 Extension Bulk Update from Bulks Certificates 

### ISSUE THREAD

**Issue by NoNamePowershell** [PKISolutions/PSPKI#126]
Hello  Hello! 
Did anyone of you try to export the bulks request certificate with Base 64 extension?

Because it Is easy to download the Certificate with RawCertificate and save it to cert extension but it is not the same.

When you download the Certificate and try to convert locally via certutil or PowerShell encoding.

So my question is.? It is possible to download a bulk certificate request from CA? Using Powershell / PSPKI module?

**Comment by Crypt32** [comment]
Sorry, I don't understand your problem. Can you tell what you did, what you get and what you want to get?

**Comment by NoNamePowershell** [comment]
ofc import-module pspki : ) 

$CA3 = "XYZ"
$CommonName = (Get-ADUser -Identity $ENV:Username).name



$Cert = Get-CertificationAuthority -ComputerName $CA3 | Get-IssuedRequest -Filter "Request.RequesterName -eq DIR\$($CommonName)" , "Request.SubmittedWhen -gt $((Get-Date).Adddays(-10))" -Property *

foreach ($cer in $Cert) {


$Export = "$Env:userprofile\Desktop\NonDomianCert\$($Cer.Commonname).cer"

$Cer.RawCertificate | Out-File -FilePath $Export

$Export2 = "$Env:userprofile\Desktop\NonDomian64\$($Cer.Commonname).cer"

certutil.exe -encode $Export $Export2
}


Code is taking the attribute  Rawrequest - and saving in on the location.

and Certutil is encoding the Certificate locally - so when you want to send to the customer following certificate it is no working.


That why I write that post ... How to download / export ( Bulk - f.e 20 / 100 ) Certificates from CA  in Base 64 Extension : 

Manual : 

https://social.technet.microsoft.com/Forums/en-US/37a213b9-f185-482e-b610-295f2056506e/export-certificate-using-base-64-cer-format-with-powershell-?forum=winserversecurity

But I don't want to manually export I would like to export it with Powershell.
Please be aware that I am on Jump host / Stephost / Stepstone ^^ whatever...  and I am not Locally logged on the CA server.

**Comment by Crypt32** [comment]
``` PowerShell
foreach ($cer in $Cert) {
$Export = "$Env:userprofile\Desktop\NonDomianCert$($Cer.Commonname).cer"
$t = @"
-----BEGIN CERTIFICATE-----
{0}
-----END CERTIFICATE-----
"@
$t -f $cer.RawCertificate.TrimEnd() | Out-File -FilePath $Export
}
```
