### ISSUE TITLE
Submit-CertificateRequest - Attributes for SAN syntax

### ISSUE THREAD

**Issue by elflan** [PKISolutions/PSPKI#127]
Hi,

I’m getting some difficulties to find examples on how to use the cmdlet _Submit-CertificateRequest_ with combined custom attributes that would include additional Subject Alternative Names (SAN).

Do you have any example on how to use the Attribute parameter which includes CertificateTemplate and SAN attributes?

Thanks

**Comment by Crypt32** [comment]
something like this:

```
Submit-CertificateRequest  -CA $CA -Path $PathToRequest -Attribute "CertificateTemplate:TemplateCN", "SAN:DNS=name1&DNS=name2"
```
