### ISSUE TITLE
Set-AuthorityInformationAccess Errors on Windows 2019 server GUI

### ISSUE THREAD

**Issue by stephaneschaumburg** [PKISolutions/PSPKI#133]
Hi
I am using the last version of PSPKI module.  My Goal is to perform a full 3 tier PKI installation in a Lab and then to pass the procedure to another team to double check my documentation.
So i've installed the root and began to define the CDP and AIA.
For the CDP, everyting went fine.

The problems appears on the AIA.  First the Get-certificationAuthority trows an error but works 
![PSPKI_get-certificationauthority](https://user-images.githubusercontent.com/38749181/98371081-e447c480-203b-11eb-8092-3d12cf403193.png)

The returned object is of a correct type : 
![PSPKI_get-certificationauthority](https://user-images.githubusercontent.com/38749181/98371947-4bb24400-203d-11eb-9d50-bb6fa6046b09.png)

When I want to remove all AIAs to add the correct ones an error Occurs IF I WANT TO USE Set-AuthorityInformationAccess.
![RemoveAIAWithoutSettingaccess](https://user-images.githubusercontent.com/38749181/98372232-ba8f9d00-203d-11eb-8ea9-563adc0f6f38.png)
![RemoveAIAAndSettingsAccess](https://user-images.githubusercontent.com/38749181/98372368-edd22c00-203d-11eb-856c-8330de21c2b2.png)

Kind Regards

**Comment by Crypt32** [comment]
If host is not domain-joined, then you have to use `Connect-CertificationAuthority` command instead of `Get-CertificationAuthority`.

**Comment by stephaneschaumburg** [comment]
My bad
Sorry , I should not have disturbed you for this one.

**Comment by Crypt32** [comment]
Is your issue solved?

**Comment by stephaneschaumburg** [comment]
Nope
[cid:image001.png@01D6B451.23713260]

**Comment by Crypt32** [comment]
Please update your issue with information you get when using `Connect-CertificationAuthority` command.

**Comment by stephaneschaumburg** [comment]
Basically same behavior no matter if I use connect-certificationauthority or get-certificationauthority

[cid:image001.png@01D6B452.BCE376F0]

Now I try to remove
[cid:image002.png@01D6B452.BCE376F0]

**Comment by stephaneschaumburg** [comment]
Hi Vadim

An update on my issue.

I usually remove all AIA information to recreate it.  I do this because I don’t want the server name to appear anywhere.
So I tried to do the same using your module.
This I used the connect-certificationAuthority | get-AuthorityInformationAccess | remove-AuthorityinformationAccess -uri *  and this works.
If I add the set-authorityInformationAcesss, it trows an error as described in my previous post.  So instead of removing all AIAs and then adding the new ones, I tried to remove one and create it replacement ….this works
So your  set-AuthorityinformationAccess cannot write an empty list

Kind regards

**Comment by Crypt32** [comment]
can you post stack trace from error?

```
$error[0].Exception.InnerException.StackTrace
```
I will review this.

**Comment by stephaneschaumburg** [comment]
[cid:image001.png@01D6B684.0F9E28D0]

I can go on.  I remove one, replace it.  Remove the next one, replace it….

**Comment by stephaneschaumburg** [comment]
Hi again Vadim.

Wen adding AIA is ther a way to specify  if it must be included in the issued certificate extensions ?

**Comment by Crypt32** [comment]
Just add `2` as prefix, e.g.: `2:http://yoururl`.

**Comment by stephaneschaumburg** [comment]
Found it after asking.  Thanks.

**Comment by stephaneschaumburg** [comment]
Hi I’ve found the commands to define the certificate validity period for enterprise Cas.
Is there a command to do this for the root ?
Otherwise I can use setreg but I’d like to use all commands from your module.

Regards.

**Comment by Crypt32** [comment]
These commands can be used for root/standalone CAs as well. In all examples, replace `Get-CertificationAuhority` with `Connect-CertificationAuthority`. And please, create separate threads for different topics.
