### ISSUE TITLE
VerboseForegroundColor not offered on every PowerShell Hosts

### ISSUE THREAD

**Issue by PChipVIA** [PKISolutions/PSPKI#135]
Hi

Would it be possible to remove the lines from Get-EnterprisePKIHealthStatus:
`$Host.PrivateData.VerboseForegroundColor
$Host.PrivateData.DebugForegroundColor`

Not every PowerShell Host allows for this.  I am using OpsMgr PowerShell Host v7.0.5000.0 which does not.

Thanks!

**Comment by Crypt32** [comment]
I agree that not every host has colors. I will leave custom colors, just add conditional checks before applying them.

**Comment by Crypt32** [comment]
I'm looking at the code and see that this was resolved long ago.
