### ISSUE TITLE
unrevoke not working

### ISSUE THREAD

**Issue by sdruessel** [PKISolutions/PSPKI#146]
I can get revoke to work with reason of "HOLD"

foreach ($laptop in $lost)
     {
     foreach ($domain in $domains)
         {
get-CertificationAuthority "$CA" | Get-IssuedRequest -Filter "CommonName -eq $laptop$domain" | Revoke-Certificate -Reason "Hold" | Out-File "C:\Program Files\ADCS\Backup\CertHOLDmachinesfromPKADLABV2SHA256.txt" -Append
         }
     }

However, a similar piece of code to unrevoke the the certificates on HOLD does not work

foreach ($machine in $found)
     {
     foreach ($domain in $domains)
         {
get-CertificationAuthority "$CA" | Get-IssuedRequest -Filter "CommonName -eq $machine$domain" | Revoke-Certificate -Reason "Unrevoke" | Out-File "C:\Program Files\ADCS\Backup\UnrevokemachinesfromPKADLABV2SHA256.txt" -Append
         }
     }

Please advise.

**Comment by Crypt32** [comment]
When you unrevoke, you have to use `Get-RevokedRequest` instead of `Get-IssuedRequest`, because you can unrevoke only revoked requests.

**Comment by Crypt32** [comment]
Closed due to inactivity.
