### ISSUE TITLE
Set-OnlineResponderRevocationConfiguration Cannot find an overload for "Oid2"

### ISSUE THREAD

**Issue by bencoremans** [PKISolutions/PSPKI#148]
Why is this cmdlet failing with "Cannot find an overload  for "Oid2" and the argument count: "1"."?

Connect-OnlineResponder $ArrayController | Get-OnlineResponderRevocationConfiguration -Name "$($OcspSigningCA.displayname)" | Set-OnlineResponderRevocationConfiguration `
        -SigningCertTemplate "$SigningCertificateTemplate" `
        -SigningServer $OcspSigningCA `
        -SigningFlag "Silent, SigningCertAutoRenewal, ForceDelegatedCert, AutoDiscoverSigninCert, ResponderIdKeyHash, SigningCertAutoEnrollment" `
        -BaseCrlUrl "http://cdp-nac.tenant19.nl/pki/tenant19-eca.crl" `
        -DeltaCrlUrl "http://cdp-nac.tenant19.nl/pki/tenant19-eca+.crl" `
        -HashAlgorithm (New-Object System.Security.Cryptography.Oid2 "sha256")

ErrorRecord                 : Cannot find an overload for "Oid2" and the argument count: "1".
WasThrownFromThrowStatement : False
Message                     : Cannot find an overload for "Oid2" and the argument count: "1".
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : System.Management.Automation.MethodException: Cannot find an overload for "Oid2" and the
                              argument count: "1".
                                 at System.Management.Automation.Adapter.GetBestMethodAndArguments(String methodName, M
                              ethodInformation[] methods, PSMethodInvocationConstraints invocationConstraints, Object[]
                               arguments, Object[]& newArguments)
                                 at System.Management.Automation.DotNetAdapter.ConstructorInvokeDotNet(Type type, Const
                              ructorInfo[] constructors, Object[] arguments)
                                 at Microsoft.PowerShell.Commands.NewObjectCommand.CallConstructor(Type type, Construct
                              orInfo[] constructors, Object[] args)
TargetSite                  : System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject] Invoke
                              (System.Collections.IEnumerable)
StackTrace                  :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                                 at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception
                              & exceptionThrown, ExecutionOptions options)
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087

**Comment by ToHo14** [comment]
I think that's an error in the example. Use:

`New-Object System.Security.Cryptography.Oid2 "sha256", $true`

The $true add the end is for directory lookup. If set to $false only local registry is queried.

**Comment by Crypt32** [comment]
Yes, it is doc bug. In your case, last parameter should be `$false`. `$true` is necessary only when lookup for:
- certificate templates
- custom application policies (or EKU)
- custom issuance/certificate policies

in all other cases it should be `$false` to speedup the lookup process, because other OID groups cannot be registered in AD.

**Comment by Crypt32** [comment]
Fixed in [v4.0.0](https://github.com/PKISolutions/PSPKI/releases/tag/v4.0.0)
