### ISSUE TITLE
Is there already an existing powershell (PSPKI) function to get the base64/Binary from the CA's issued certificate folder?

### ISSUE THREAD

**Issue by bencoremans** [PKISolutions/PSPKI#150]
My use case is to enroll a certificate from a template, but in this case the manager has to approve the certificate first.
So I need to build a flow to: 
- Request a certificate from template. (I use `ComObject X509Enrollment.CX509Enrollment` for this to get the request ID back. `Get-Certificate` doesn't do that.)
- Approve the request from pending requests. (I use PSPKI `Approve-CertificateRequest`)
- Read Base64 from CA. (I use this example: https://www.sysadmins.lv/retired-msft-blogs/alejacma/how-to-export-issued-certificates-from-a-ca-programatically-powershell.aspx)
- Return Base64 to server to install the certificate. (I use `ComObject X509Enrollment.CX509Enrollment` for this.)

It's working but a bit complex. If there are PSPKI functions for this I would like to know and implement them? Or if you have a better idea to accomplish the task, I would like to know to. Thank you.

**Comment by bencoremans** [comment]
Thank you! This makes it much easier.

**Comment by Crypt32** [comment]
Funny fact that even I don't remember entire functionality of PSPKI, but there is a one-liner:
``` PowerShell
$cert = Get-CA myca.example.com | Get-IssuedRequest -RequestID 123 | Receive-Certificate
```
or if you want to save it to a file (additionally), then:
``` PowerShell
$cert = Get-CA myca.example.com | Get-IssuedRequest -RequestID 123 | Receive-Certificate -Path C:\test
```
`-Path` parameter accepts path to a folder (not file) and file name will be `RequestID_$ID.cer`. And `$cert` variable will be populated with certificate object in all cases.

**Comment by bencoremans** [comment]
Which command can I use to install the certificate from $cert?

**Comment by Crypt32** [comment]
The easiest way is to use `certreq -accept` for machine certificate and `certreq -user -accept` for user certificate. I don't have replacement command.

**Comment by bencoremans** [comment]
Now I am using your example to install the certificate from $cert
https://www.sysadmins.lv/blog-en/configure-iis-web-administration-to-use-centralized-ssl-certificate.aspx

**Comment by Crypt32** [comment]
Good. If you don't mind, create a new issue with request to add `Install-CertificateResponse` command to PSPKI module. I will close this issue as solved.

**Comment by bencoremans** [comment]
I will do that. Thank you
