### ISSUE TITLE
Passing custom credentials

### ISSUE THREAD

**Issue by be1t1s** [PKISolutions/PSPKI#152]
Hi everyone, i am looking at how i can pass credentials to commands, is this possible? Am I missing something?

**Comment by Crypt32** [comment]
No, custom credentials are not supported due to the way how API interacts with underlying DCOM interfaces. Best practice is to run the module under account that has appropriate permissions on target servers (CA, OCSP, AD).

**Comment by Crypt32** [comment]
Closed due to thread inactivity.
