### ISSUE TITLE
Convert-PemToPfx  returns 'The property 'PrivateKey'  cannot be found on this object'

### ISSUE THREAD

**Issue by BZanten** [PKISolutions/PSPKI#155]
I have a certificate in PFX that I converted to PEM using  Convert-PfxToPem  resulting in a PEM file.

If I now try to import or convert this PEM file back into certificate or PFX file, I'm getting the error:
Convert-PemToPfx : The property 'PrivateKey' cannot be found on this object. Verify that the property exists and can be set.

Note: that when I download a similar function from: https://gist.github.com/ChrisLynchHPE/a99fe45d48f427ef4a45c4d44623f262   
 or from your own site: https://www.sysadmins.lv/blog-en/how-to-convert-pem-to-x509certificate2-in-powershell-revisited.aspx (Convert-PemToPfx  seems to be a nearly identical to this function), 
then RENAME that function : to Convert-Pem2Pfx ("To"->"2"),  so that I have both versions of the function side-by-side this other function _does_ work.

![Convert-PemToPfx](https://user-images.githubusercontent.com/18613289/124121064-bd2f7e80-da74-11eb-8460-2708c27a57d2.png)

**Comment by exchange12rocks** [comment]
This happens because the variable `$script:Cert` is empty in the function `__attachPrivateKey`. I see two possible solutions here:

- Either pass `$Cert` to `__attachPrivateKey` by value and return two objects: `$Cert` and `$rsa`, therefore changing the function call to `$Cert, $rsaKey = __attachPrivateKey $PrivateKey $Cert`
- Or to pass `$Cert` to `__attachPrivateKey` by reference.

**Comment by AbbasRashidi** [comment]
Hi, I still have the same issue with the latest version of the module. And I changed $script:Cert as mentioned above in $Cert and it works. 
As I see, this Issue report is quite old. Is somebody still working on this module and fixes some bugs?

**Comment by Crypt32** [comment]
Unfortunately, the module is on a slow maintenance due to limited time. I have no ETA for next release, unfortunately.

**Comment by AbbasRashidi** [comment]
@Crypt32  Thank you for the response. I understand. Is there a button "Insert a coin" ;-)

**Comment by Crypt32** [comment]
This issue is fixed via https://github.com/PKISolutions/PSPKI/issues/145. Referenced issue is slightly different from this, but it resulted in complete function re-write. Updated function should automatically resolve this issue.

**Comment by Crypt32** [comment]
fixed in v4.2
