### ISSUE TITLE
Submit-CertificateRequest issue with a wrong method name

### ISSUE THREAD

**Issue by StephanePiet** [PKISolutions/PSPKI#158]
There is an issue with the function Submit-CertificateRequest:
Method invocation failed because [PKI.CertificateServices.CertificateAuthority] does not contain a method named 'PingRequest'.

In fact the available method is Ping and not PingRequest. Can you change this ?

Regards,

Stéphane

**Comment by Crypt32** [comment]
Actually, there is such method: https://github.com/PKISolutions/pkix.net/blob/808db9c106679544744be762bd50e02ce3c2850d/PKI/CertificateServices/CertificateAuthority.cs#L414. I've updated reference libraries.

**Comment by StephanePiet** [comment]
Thanks for the update :)
