### ISSUE TITLE
Typedata error when importing PSPKI module at console session

### ISSUE THREAD

**Issue by hmiller10** [PKISolutions/PSPKI#161]
I received this error when importing the PSPKI module, version 3.7.2, from an elevated PowerShell session.

PS C:\scripts> ipmo pspki
Update-TypeData : Error in TypeData "System.Security.Cryptography.Oid": The member ToString is already present.
At C:\Program Files\WindowsPowerShell\Modules\pspki\3.7.2\PSPKI.psm1:287 char:5
+     Update-TypeData -AppendPath $PSScriptRoot\Types\PSPKI.PS5Types.ps ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Update-TypeData], RuntimeException
    + FullyQualifiedErrorId : TypesXmlUpdateException,Microsoft.PowerShell.Commands.UpdateTypeDataCommand

I have never received this before. Even after running Remove-Module PSPKI and re-importing the module the same error appears.  What is happening to cause this error to be thrown?

**Comment by Crypt32** [comment]
Closed as stale.

**Comment by MickaelRoy** [comment]
This bug is still present on version 4.3.0.
