### ISSUE TITLE
Get-CATemplate throws an error "New-Object : Exception calling ".ctor" with "1" argument(s): "There is no such object on the server."

### ISSUE THREAD

**Issue by miasik** [PKISolutions/PSPKI#164]
It looks similar to #160 
```powershell
PS C:\Users\QQQ> Get-CertificationAuthority | Get-CATemplate -Debug
New-Object : Exception calling ".ctor" with "1" argument(s): "There is no such object on the server.
"
At C:\Users\QQQ\Documents\WindowsPowerShell\Modules\PSPKI\3.7.2\Server\Get-CATemplate.ps1:14 char:4
+             New-Object PKI.CertificateServices.CATemplate -ArgumentLi ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
```

**Comment by Crypt32** [comment]
I think this is a different issue. The error is thrown from LDAP accessor. It may indicate that CA has assigned a certificate template which no longer exist in Active Directory. If you open your CA in MMC and navigate to Certificate Templates folder you should see a template with red cross on template icon.

**Comment by miasik** [comment]
I've just checked. No, I don't have a red cross over our assigned template's icons
![изображение](https://user-images.githubusercontent.com/1073832/147541324-bf5e3955-ab44-465c-b6b1-0f8f8743e5fe.png)

**Comment by Crypt32** [comment]
then it is something with AD. Here is where `CATemplate` attempts to find the certificate template in AD: https://github.com/PKISolutions/pkix.net/blob/f77ec6d1e4d23ac87a6a427b835724839b10f856/PKI/CertificateServices/CATemplate.cs#L77 and the exception is most likely thrown there.

**Comment by Crypt32** [comment]
Closed as non-reproducable.
