### ISSUE TITLE
Get-CertificationAuthority writes error about GetAdPkiContainer when run in Invoke-Command

### ISSUE THREAD

**Issue by danielniccoli** [PKISolutions/PSPKI#171]
Running Get-CertificationAuthority on a remote machine throws an exception:

```PowerShell
$pss = New-PSSession "ComputerName" -Credential $c
Invoke-Command -Session $pss {
    Get-CertificationAuthority "ComputerName"
}
```
writes a warning (non-terminating)

> MethodInvocationException: Exception calling "GetAdPkiContainer" with "1" argument(s): "An operations error occurred."

However, the command returns a working object.

**Comment by Crypt32** [comment]
This is expected due to [double hop](https://techcommunity.microsoft.com/t5/ask-the-directory-services-team/understanding-kerberos-double-hop/ba-p/395463) authentication issue. PSPKI is not fully supported and never will be supported in PowerShell remote sessions because of this.
