### ISSUE TITLE
Get-IssuedRequest CERTSRV_E_ENROLL_DENIED error

### ISSUE THREAD

**Issue by premfix** [PKISolutions/PSPKI#173]
Hello.

I try to get issued certs with "Get-IssuedRequest -CertificationAuthority ca01", but I receive this error:
```
Get-IssuedRequest : Cannot process argument transformation on parameter 'CertificationAuthority'. Cannot convert value
"ca01" to type "PKI.CertificateServices.CertificateAuthority[]". Error: "Cannot convert value "ca01"
to type "PKI.CertificateServices.CertificateAuthority". Error: "CCertRequest::GetCAProperty: The permissions on this
certification authority do not allow the current user to enroll for certificates. 0x80094011 (-2146877423
CERTSRV_E_ENROLL_DENIED)""
At line:1 char:47
+ Get-IssuedRequest -CertificationAuthority ca01
+                                               ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-IssuedRequest], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-IssuedRequest
```

At the same time I can get issued certs from ca01 with certutil command with no issues:
certutil -config "ca01.abc.com\Test Issuing CA" -view -restrict "Disposition=20" -out SerialNumber csv

User account that I use, has only read permissions on the CA itself. 
But if I grant for this user permission to request certificates - I can get issued certs with Get-IssuedRequest cmdlet.

CA has restrictions on who can request certificates, that's why I want user account, that I use to get issued certs, to have only read permissions on the CA itself. I need this to collect statistical data for the issued certs.

Thank you.

**Comment by Crypt32** [comment]
It doesn't work this way. `-CertificationAuthority` parameter expects an object, not a string the object can be constructed from. Sometimes it works, sometimes it doesn't, because parameter accepts an array. You need to rewrite your code to construct CA object first and then pass to pipeline:

``` PowerShell
Connect-CA "ca01" | Get-IssuedRequest
```

> User account that I use, has only read permissions on the CA itself.

yes, Read permissions on CA are sufficient to allow DB queries.

**Comment by premfix** [comment]
Thank you for your quick response.

When I try to run Connect-CertificationAuthority ca01.abc.com, I receive the same error - CERTSRV_E_ENROLL_DENIED:
```
Connect-CertificationAuthority ca01.abc.com
Exception calling "Connect" with "1" argument(s): "CCertRequest::GetCAProperty: The permissions on this certification
authority do not allow the current user to enroll for certificates. 0x80094011 (-2146877423 CERTSRV_E_ENROLL_DENIED)"
At C:\Program Files\WindowsPowerShell\Modules\pspki\3.7.2\Server\Connect-CertificationAuthority.ps1:13 char:4
+             [PKI.CertificateServices.CertificateAuthority]::Connect($ ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : COMException
```

And only with "request certificates" permission I can successfully connect to CA with Connect-CA cmdlet. But I want to avoid granting this permission to the account I use.

**Comment by Crypt32** [comment]
By default, Authenticated Users group has Enroll permission, so any authenticated account implies Enroll permission. The error indicates that you have modified this. You need to have Enroll permission to read properties from CA. CA Database view requires Read permission.

**Comment by premfix** [comment]
That's correct, Authenticated Users group either has read only permissions or completely removed from ACL.
I expected that this cmdlet would allow to read CA DB with the same permission (read only) as other tools (certutil and CA mmc console) allow. But if it requires Enroll permission to read CA's DB, then I'll stick with certutil.

Thank you for the clarification, awesome articles and PSPKI module!
