### ISSUE TITLE
Multiple CAs

### ISSUE THREAD

**Issue by karthikeyanrathore** [PKISolutions/PSPKI#184]
Is it possible to create more than 1 certification authority on a single windows ADCS server using this command : 
`Install-CertificationAuthority` https://www.pkisolutions.com/tools/pspki/Install-CertificationAuthority/

**Comment by Crypt32** [comment]
No, ADCS supports only one instance of CA installation per server.

**Comment by karthikeyanrathore** [comment]
ahh okay :(
