### ISSUE TITLE
Installing In Controlled Environments

### ISSUE THREAD

**Issue by dtklein** [PKISolutions/PSPKI#186]
If this is already documented and I missed it, apologies for the repeat, and a pointer to the existing doc would be appreciated. 

For those working in controlled environments, where this would need to be brought into an internal repository (after being vetted, scanned, etc), are there direct URLs to the package and/or installer? I'm speaking with someone who cannot use "Install-Package" or NuGet, and would like to know if there is a releases page with direct links to retrieve the recent versions of this, for onboarding to the internal repository system.

**Comment by Crypt32** [comment]
Hmm...it seems PowerShell gallery doesn't support ZIP package download. The only way I'm aware of is to install module on a computer where Nuget/PS gallery is enabled and then copy installed files to destination environment. All files that support signing are digitally signed, so you can check files integrity.

Alternatively, you can download raw Nuget package: https://www.powershellgallery.com/packages/PSPKI/:
![image](https://user-images.githubusercontent.com/6384119/211876067-42f07173-1c66-436f-8cc2-b2d8e613d111.png)
and rename file extension from `.nupkg` to `.zip`.
![image](https://user-images.githubusercontent.com/6384119/211876511-9c700878-8ad9-41be-b5ee-ef46256e0ad1.png)
stripped lines are irrelevant to module files which are safe to delete.

**Comment by dtklein** [comment]
Thank you very much. I'll see if I can spin up a Windows VM on a red-network, install via the nupkg, bundle it on removable media, and bring it for scanning, ingestion, etc, to place on internal repo on the black network. 

@Crypt32, thank you for this awesome tool (this is not the first org I have been showing it to) and for being so wonderfully responsive to weird environments and questions.
