### ISSUE TITLE
Cannot find type [Security.Cryptography.Oid2] issue

### ISSUE THREAD

**Issue by IBluZI** [PKISolutions/PSPKI#193]
Hi. In version 3.7.2 this command 

`New-SelfSignedCertificateEx -Subject 'CN=exampledomain.com' -ProviderName "Microsoft Enhanced RSA and AES Cryptographic Provider" -KeyLength 2048 -FriendlyName 'ADFS SelfSigned' -SignatureAlgorithm sha256 -EKU "Server Authentication", "Client authentication" -KeyUsage "KeyEncipherment, DigitalSignature" -Exportable -StoreLocation "LocalMachine"`

executes suceessfully. But in version 4.0 I have this error

> >>
> New-Object : Cannot find type [Security.Cryptography.Oid2]: verify that the assembly containing this type is loaded.
> At C:\Program Files\WindowsPowerShell\Modules\PSPKI\4.0.0\Client\New-SelfSignedCertificateEx.ps1:64 char:33
> + ... Algorithm = New-Object Security.Cryptography.Oid2 $SignatureAlgorithm ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
>     + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

Fix this please.

**Comment by Crypt32** [comment]
fixed in v4.2
