### ISSUE TITLE
Feature request: get encrypted key from CA database

### ISSUE THREAD

**Issue by hmiller10** [PKISolutions/PSPKI#196]
Would like to have cmdlet added that would perform certificate recoveries from a CA database tagged with the KRA certificate such as sMIME and EFS certificates.

EG: $Request = Get-IssuedRequest -CertificatationAuthoriy myCA.domain.com -Filter "Request.RequesterName -eq 'JDoe'"

Then mimic certutil.exe -config $ConfigString -p $Password -GetKey $Request.SerialNumber recover $FileName

**Comment by Crypt32** [comment]
This command will be available in PSPKI v4.1

**Comment by Crypt32** [comment]
added in v4.2
