### ISSUE TITLE
PSPKI 3.7.2.5

### ISSUE THREAD

**Issue by bencoremans** [PKISolutions/PSPKI#200]
Hi Vadims,

Currently, in our environment, we are utilizing version 3.7.2 of the PSPKI module, which includes a replaced version of SysadminsLV.PKI.dll (specifically, version 3.7.2.5). This replacement was sourced from the GitHub issue https://github.com/PKISolutions/PSPKI/issues/129#issuecomment-722561086.

I wanted to inquire if it would be possible for you to upload a new package of PSPKI, labeled as version 3.7.2.5, which incorporates the updated DLL, either to the PowerShell Gallery or within the PKISolutions space specifically for the enterprise version?

In our environment, we rely on the nupkg file to facilitate the import process into our internal gallery.

Please note that we plan to implement version 4 of PSPKI at a later stage, once we have completed the necessary testing.

Thank you for your assistance.

Kind regards,
Ben

**Comment by Crypt32** [comment]
I will need a kind of wayback machine to get the right sources.

Do I understand it correctly that you basically want a 3.7.2 version with updated PKI library that addresses cert template ACL? And would like to know if PKI library v3.2.7.5 helped you. If so, I can get use that attached library, sign and add to PSPKI v3.7.2 RTM module.

**Comment by bencoremans** [comment]
Hi Vadims,

Thank you for your understanding. Yes, you've got it right—we are seeking a version 3.7.2 update incorporating the improved PKI library that effectively addresses the certificate template ACL issue. The SysadminsLV.PKI.dll (version 3.7.2.5) library has indeed proven to be instrumental in resolving the problem.

We appreciate your assistance in signing and integrating this updated PKI library into the PSPKI v3.7.2 RTM module. This will greatly support our ongoing operations until we transition to version 4 of PSPKI after completing our thorough testing.

Looking forward to the updated package and your continued support.

Best regards,
Ben

**Comment by Crypt32** [comment]
Unfortunately my allowed time to work on PSPKI is quite limited and current v4.2 version is stable enough to use, thus I have no plans to provide a fix specifically for v3.7.2.
