### ISSUE TITLE
Convert-PemToPfx returns Method invocation failed because [SysadminsLV.Asn1Parser.Asn1Reader] does not contain a method named 'MoveNextCurrentLevel'

### ISSUE THREAD

**Issue by fadi-scavo** [PKISolutions/PSPKI#203]

**Comment by Crypt32** [comment]
This was fixed in a0f4524ce6cf5c23a2a423c65b4fab9ec6aa4ec2 during function complete rewrite.

**Comment by fadi-scavo** [comment]
Is it already included in the version 4.0.0 ?
https://www.powershellgallery.com/packages/PSPKI/4.0.0

**Comment by Crypt32** [comment]
Nope, it is part of upcoming 4.2.

**Comment by Crypt32** [comment]
fixed in v4.2
