### ISSUE TITLE
Receive-Certificate retrieve .p7b formatted certificate

### ISSUE THREAD

**Issue by hmiller10** [PKISolutions/PSPKI#209]
Hello,

Is there a way, using the PSPKI module to retrieve an issued certificate from the CA database in .p7b format? We are trying to automate our Linux and MAC certificate processing and receive-certificate seems to only retrieve a .cer formatted certificate.

Is it possible to get .p7b certificate bundle? If not, could we make this a feature request?

**Comment by Crypt32** [comment]
Currently, it is not supported, but it is possible to add this functionality

**Comment by Crypt32** [comment]
It is implemented via new `-IncludeChain` switch parameter.
