### ISSUE TITLE
"Get-CA -Name $CAName | Get-EnterprisePKIHealthStatus" returns error "Method invocation failed because [SysadminsLV.Asn1Parser.Asn1Utils] does not contain a method named 'DecodeInteger' "

### ISSUE THREAD

**Issue by MikeSouthwell** [PKISolutions/PSPKI#212]
I'm getting this error when trying to run Get-EnterprisePKIHealthStatus on the Get-CA command after looking up our FAS server's CA certificate. I'm using version 4.2.0 of PSPKI.

**"Method invocation failed because [SysadminsLV.Asn1Parser.Asn1Utils] does not contain a method named 'DecodeInteger' "**

The command works fine on the Secondary CA server up the chain that the FAS servers use to get their certificates so I'm not sure what I'm doing wrong?

Also the primary root CA just returns null.

Primary CA (null)
      Secondary CA (working)
              Tertiary CAs [FAS machines] (error)

**Comment by Crypt32** [comment]
This has been fixed and added to next release.
