### ISSUE TITLE
Revocation Syntax for Request ID

### ISSUE THREAD

**Issue by Flyslinger2** [PKISolutions/PSPKI#217]
I need to revoke certs based on the Request ID. I've scoured the interwebs and have not had any luck.

Can someone please provide an example? 

Thanks

**Comment by Crypt32** [comment]
Have you looked Revoke-Certificate command examples: https://www.pkisolutions.com/tools/pspki/Revoke-Certificate?

**Comment by Flyslinger2** [comment]
Yes. I referenced that before submitting the ticket. I want to filter on Request ID.


Mark R. Sigsbee, CISSP



[cid:c8e17d94-2789-4d90-8531-0dccd7e98acd]<https://www.linkedin.com/in/mark-sigsbee/>

SUNet PKI Support Team

***@***.******@***.***>

(301)509-7592 (cell)



[cid:03d8d51e-8174-47fd-829a-e74fe472db19]

________________________________

**Comment by Crypt32** [comment]
Look at the last example. Just replace `Get-RevokedCertificate` with `Get-IssuedCertificate`, for example:
```
Get-CertificationAuthority MyCA | Get-IssuedRequest -ID 17 | Revoke-Certificate -Reason "KeyCompromise"
```

**Comment by Flyslinger2** [comment]
Nothing happens with this syntax. Powershell comes back with a prompt immediately.  No error messages and cert status never changes.


Mark R. Sigsbee, CISSP



[cid:ac62bff1-56e5-44e8-8e26-39d4da418860]<https://www.linkedin.com/in/mark-sigsbee/>

SUNet PKI Support Team

***@***.******@***.***>

(301)509-7592 (cell)



[cid:b685f415-c067-4b63-b06e-1eb7fe936a37]

________________________________

**Comment by Crypt32** [comment]
Then your command has incorrect parameters.

**Comment by Flyslinger2** [comment]
Attached is a screen shot of my command. Sadly I live in the air-gapped world so I have no capabilities to copy down files.

![Revoke Issue](https://github.com/PKISolutions/PSPKI/assets/38768547/b47c5fdd-01eb-4b14-b94c-722bc39368f1)

**Comment by Crypt32** [comment]
And what your text file content look like?

**Comment by Flyslinger2** [comment]
![Revoke Issue REQ ID List](https://github.com/PKISolutions/PSPKI/assets/38768547/fa7269a9-f8a2-4dbc-aad4-6c7f452b4492)

**Comment by Flyslinger2** [comment]
Resolved the issue. I had to use FQDN in replacement of "MyCA".
