### ISSUE TITLE
Set-Content error when running New-SelfSignedCertificateEx on PowerShell 6.0

### ISSUE THREAD

**Issue by kevinlo** [PKISolutions/PSPKI#45]
Because of this change [PowerShell Core does not have -Encoding Byte. Replaced with new parameter AsByteStream](https://www.jonathanmedd.net/2017/12/powershell-core-does-not-have-encoding-byte-replaced-with-new-parameter-asbytestream.html), 

The following line has error when running on Powershell 6.0

`			Set-Content -Path $Path -Value ([Convert]::FromBase64String($PFXString)) -Encoding Byte
`

Any plan to have a version that can run on both PowerShell Core and PowerShell Windows?

Thanks.

**Comment by Crypt32** [comment]
Reopenning. Going to make requested changes.

**Comment by Crypt32** [comment]
Linked: https://github.com/PKISolutions/PSPKI/issues/104
