### ISSUE TITLE
New-SelfSignedCertificateEx FriendlyName option

### ISSUE THREAD

**Issue by Ratmaniac82** [PKISolutions/PSPKI#58]
When I create a certificate with FriendlyName option if I check Friendly Name property last character is missing.

Ex. I call it SelfSignedCert but in certificate property friendly name is SelfSignedCer

**Comment by Crypt32** [comment]
I can confirm this issue, but yet can’t find a solution. There is something wrong with a unmanaged function call that sets the friendly name.
