### ISSUE TITLE
Get-EnterPrisePKIHealthStatus.ps1 - Exception calling "SendRequest" with "0" argument(s): "Input data is not valid ASN-encoded GENERALIZED TIME."

### ISSUE THREAD

**Issue by shappee747** [PKISolutions/PSPKI#59]
Hi there,

Runing PSPKI 3.4.1.0 on Powershell 4.0 I am faced with a problem in the above script line 456 - $resp = $req.SendRequest(). To find the problem I commented out the try catch block around it. Once the method is called I get this:

Exception calling "SendRequest" with "0" argument(s): "Input data is not valid ASN-encoded GENERALIZED TIME."

I've seen this exception here: https://github.com/Crypt32/PSPKI/issues/55 but this time the conversion seems to happen within the library, which I'm not able to recompile.

Thx for helping me out.

**Comment by Crypt32** [comment]
I will take a look. Unfortunately, I’m very busy on other duties, but will try to check this by the end of week. It woukd be great if you could post a stack trace:

`$error[0].exception.innerexception.stacktrace`

**Comment by shappee747** [comment]
Hi, thx for looking into this. Here is the stacktrace:

   at SysadminsLV.Asn1Parser.Asn1Utils.DecodeGeneralizedTime(Byte[] rawData)
   at PKI.OCSP.OCSPResponse.decodeTbsResponse(Asn1Reader tbsResponseData)
   at PKI.OCSP.OCSPResponse.verifyAll(Asn1Reader tbsResponseData, Byte[] signature, Oid signatureAlgorithm)
   at PKI.OCSP.OCSPRequest.SendRequest()
   at CallSite.Target(Closure , CallSite , Object )

**Comment by Crypt32** [comment]
At first look it sounds like that OCSP responds with invalid data.

Exception occurs here: https://github.com/Crypt32/pkix.net/blob/84371e99162c91b5aba094c961aab0854d4a6c2e/PKI/OCSP/OCSPResponse.cs#L227

`ProducedAt = Asn1Utils.DecodeGeneralizedTime(tbsResponseData.GetTagRawData());`

According to RFC6960:
```
ResponseData ::= SEQUENCE {
   version             [0] EXPLICIT Version DEFAULT v1,
   responderID             ResponderID,
   producedAt              GeneralizedTime,
   responses               SEQUENCE OF SingleResponse,
   responseExtensions  [1] EXPLICIT Extensions OPTIONAL }
```
`producedAt` field is Generalized time, so I'm trying to decode it here: https://github.com/Crypt32/Asn1DerParser.NET/blob/49710a3788491aee4e45c3a7a73c6983227cfcca/Asn1Parser/Asn1Utils.cs#L250 and validate input type here: https://github.com/Crypt32/Asn1DerParser.NET/blob/49710a3788491aee4e45c3a7a73c6983227cfcca/Asn1Parser/Asn1Utils.cs#L253
```
if (asn.Tag != (Byte)Asn1Type.GeneralizedTime) {
    throw new InvalidDataException("Input data is not valid ASN-encoded GENERALIZED TIME.");
}
```
and input data is not generalized time I'm expecting, therefore throwing an exception you see.

I will check again if the code behaves as expected. If my tests are ok, then we may need to investigate what exactly returns OCSP server in your environment.

**Comment by shappee747** [comment]
OK, any idea how I can grap the response, before the exception occurs?

**Comment by Crypt32** [comment]
Here is a code snippet you can use:
``` PowerShell
$req = New-Object pki.ocsp.ocsprequest "path to CA-issued cert"
$req.Encode()
$wc = New-Object net.webclient
$wc.Headers.Add("Content-Type", "application/ocsp-request");
$wc.Headers.Add("Accept", "*/*");
$wc.Headers.Add("User-Agent", "PowerShell PKI Module");
$wc.Headers.Add("Cache-Control", "no-cache");
$wc.Headers.Add("Pragma", "no-cache");
$url = $req.URL.OriginalString.Replace("`0",$null)
if ($url.EndsWith("/")) {
    $url += [uri]::EscapeUriString([convert]::ToBase64String($req.RawData)).Replace("+", "%2b").Replace("/", "%2f").Replace("=", "%3d")
} else {
    $url += "/" + [Uri]::EscapeUriString([convert]::ToBase64String($req.RawData)).Replace("+", "%2b").Replace("/", "%2f").Replace("=", "%3d")
}
$bytes = $wc.DownloadData($url)
$response = [convert]::ToBase64String($bytes)
```
$response will contain a base64 string of raw response. I will need this data.

do not forget to specify a path to a CA-issued certificate (for example, CA Exchange certificate)

**Comment by shappee747** [comment]
Here is the response string:
`MIIFyAoBAKCCBcEwggW9BgkrBgEFBQcwAQEEggWuMIIFqjCBoaIWBBR1En9TmbzWA2ZPCgRv08cGFOEy5BgPMjAxODExMjgwNDAxMDlaMHYwdDBMMAkGBSsOAwIaBQAEFNBey+wBfhgKg4JhBYyk9qIr9as5BBQcrbKPVb6s/CVTugDQAm4s6aENLgITKAAAAriC4Gyr3g9TYAAAAAACuIAAGA8yMDE4MTEyNzA0NTAwMVqgERgPMjAxODEy
MDMyMzA4NDdaMA0GCSqGSIb3DQEBCwUAA4IBAQBAepKtn4PdFzzyNUz9C3Ap+nWX6vjI+MKsfPV+ybqb8zlDXbv2tNCUOlukhm2XLvLD041tikPKoQsCOhhAt/Mn7lK2wGq8COO06kC3fek6AH5ZPamatPmDJhuMKRYBwmkVkYuBBB+3XHiCPs54gfj9j8vvrvxHv0lQyC0u+AEWUqk31eLIXeVU4QNtrjeRX6EzVkOQFcrtM9a7e30TCa3m
d40/jl5qwPFRt1dc6gEbTA4aGg7/lF5kgI57Qop3VMCLyHDNIuA/FhR23wFVK1z2OEDOOBftBnB3hEshz8YuAciozqxPNJ3o8AlAOCPpxmHusWHyXZF/lyc1jQLejQcBoIID7jCCA+owggPmMIICzqADAgECAhMoAAACvuwJHtj2TAmVAAAAAAK+MA0GCSqGSIb3DQEBCwUAMEYxCzAJBgNVBAYTAkRFMRQwEgYDVQQKEwtTaGFycCBFVSBR
UzEhMB8GA1UEAxMYU2hhcnAgRXVyb3BlIFN1YiBDQSAzIFFTMB4XDTE4MTExOTIzMDg0N1oXDTE4MTIwMzIzMDg0N1owHjEcMBoGA1UEAxMTY3BraXEyMi5TaGFycFFTLlFkczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK7gXrFT/JnKGf3H0F2eP4Kr2f2r5E7JVEyi0B1TpbLfvr7xRl7zZb57dM/oghlBihkJ6unQJdCS
f0hH1iLc6aFD1QWRUkdl6oHTKeou9BbqE83IrI9uxiEuxcf4zrCR7eFQyLHpaQmv5SgDM+2IbvS1xpaD64iZygnsK/TQFahUjM2lYjDIl3etMczpQooetHqmWJgTaYTnvLLNWWkIFs2fqLWGqDfIffx/49OyXs2r50jD+ehfT1SHWcx5RRSCtaJ3VGAL11jOlK0OjQaWak3RjeKec8SDrPkYI0Dr7wesNctEBhczI7Jals9HbIdGeJHfE015
EDhS8EZXyW4UFSMCAwEAAaOB9DCB8TA8BgkrBgEEAYI3FQcELzAtBiUrBgEEAYI3FQiEndkOhJfMXYLtjTfz6xqysCqBIIHji2aGlvpgAgFkAgEFMBMGA1UdJQQMMAoGCCsGAQUFBwMJMA4GA1UdDwEB/wQEAwIHgDAbBgkrBgEEAYI3FQoEDjAMMAoGCCsGAQUFBwMJMA8GCSsGAQUFBzABBQQCBQAwHwYDVR0jBBgwFoAUHK2yj1W+rPwl
U7oA0AJuLOmhDS4wHQYDVR0OBBYEFHUSf1OZvNYDZk8KBG/TxwYU4TLkMB4GA1UdEQQXMBWCE2Nwa2lxMjIuU2hhcnBRUy5RZHMwDQYJKoZIhvcNAQELBQADggEBAKpcQpnf10KW2NoyvRZag+qdHJMGwTm9pwc+mLKvWqw9tvBjbwLgLza/Ifk3qG33dSsetw6g6kpfd0vFMGfSlcYPfqYwTFdEmskJXrwnrX17gIJactOuKIL/AgXKqjdK
Y1TejxCXgRjq0pRAtdG2cAvWkaNi/DYbJXbQHwhQME1iDSpCwwrsnu3WTnpyE+rFKcyfQzWFmcxmeLrlnKRrY5B1IgKNuVY4GDJ9XPZpITt0P/tTKX2uye8oZm9QohA2zyLT+cNN7Ps7TI2OeTWHzmc/2SJGYBeoAyH9O4rYiK8gx00OR126AaAtsR+IxVE881qEe9GZ7hWfwdqxd6gfXKU=`

**Comment by Crypt32** [comment]
Ok, I found the issue. This is an issue with my ASN.1 binary parser. This will require a hard work from my side in order to make a reliable fix. Unfortunately, I can't provide a hotfix right now.

My apologies that this piece failed for you.

**Comment by shappee747** [comment]
OK, nice to hear. At least you know what the problem is. No rush, but do you have an estimated guess when you will have the time?

**Comment by Crypt32** [comment]
I would put next week. That is, the fix will be available in repository next week (at least, you can compile it yourself), but in PS gallery will appear in next PSPKI release.

**Comment by Crypt32** [comment]
I fixed the issue in the ASN.1 parser library: https://github.com/Crypt32/Asn1DerParser.NET/commit/644db6d2c4e12faeb43de86460de87513f6901df
now I can decode OCSP response properly:
![capture](https://user-images.githubusercontent.com/6384119/49180787-58609480-f35e-11e8-90bc-300339ad7c40.PNG)

For testing purposes I'm attaching compiled fixed ASN parser:
[SysadminsLV.Asn1Parser.zip](https://github.com/Crypt32/PSPKI/files/2626524/SysadminsLV.Asn1Parser.zip)
Please, let me know if it works for you.

**Comment by shappee747** [comment]
Nice. Its working again. Thank you very much.
