### ISSUE TITLE
2 little fixes needed in New-SelfSignedCertificateEx

### ISSUE THREAD

**Issue by Ratmaniac82** [PKISolutions/PSPKI#60]
I've found few differences creating a self signed certificate using New-SelfSignedCertificateEx.

1) If I don't specify explicitly KeyUsage = "CRLSign, KeyCertSign" when creating a certificate with IsCA parameter, Key Usage in certificate property is "Information Not Available".
In documentation it says that if IsCA option is used KeyUsage is set to CRLSing, KeyCertSign by default.

2) If I don't specify ProvideName explicitly with ProviderName option, provider used is "Microsoft Enhanced RSA and AES Cryptographic Provider".
In documentation it says that default parameter is "Microsoft Enhanced Cryptographic Provider v1.0". (maybe I'm using Windows 2016 S.O.)

**Comment by Crypt32** [comment]
1. it is my fault. When migrated the code I simply forgot this. Will fix this.
2. Docs issue. Online version is updated to reflect actual behavior. I deprecated "Microsoft Enhanced Cryptographic Provider v1.0" default provider long ago.

**Comment by Crypt32** [comment]
First part of this issue is fixed in the code.
