### ISSUE TITLE
Add-CATemplate fails if no templates are available on CA

### ISSUE THREAD

**Issue by bencoremans** [PKISolutions/PSPKI#61]
When adding templates to a fresh Enterprise CA, the Add-CATemplate function fails.
If you add a template to the CA manually first, the function works.

Exception calling "AddRange" with "1" argument(s): "Value cannot be null.
Parameter name: collection"
At C:\Program Files\WindowsPowerShell\Modules\PSPKI\3.4.1.0\Server\Add-CATemplate.ps1:29 char:7
                         $CATemplate.AddRange($Template)
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
     FullyQualifiedErrorId : ArgumentNullException

**Comment by Crypt32** [comment]
Thanks for reporting!
The problem occurs here: https://github.com/Crypt32/pkix.net/blob/84371e99162c91b5aba094c961aab0854d4a6c2e/PKI/CertificateServices/CATemplate.cs#L121

I'm initializing a temporary collection from existing array in `Templates` property. However, it is `null` when no templates are assigned to CA: https://github.com/Crypt32/pkix.net/blob/84371e99162c91b5aba094c961aab0854d4a6c2e/PKI/CertificateServices/CATemplate.cs#L76

This code is quite old and wasn't reviewed for a while.
