### ISSUE TITLE
Rights required to run Get-EnterprisePKIHealthStatus

### ISSUE THREAD

**Issue by StevenShockley** [PKISolutions/PSPKI#63]
Is there any way to run Get-EnterprisePKIHealthStatus from a remote machine without the user being a local admin on the CA server?  I'd like to use it for CRL freshness checks, but I'd rather use a low-rights service account.  Thanks.

**Comment by Crypt32** [comment]
What error you get when you run the command with standard user permissions?

**Comment by PatrickOnGit** [comment]
Hi Steven

The account requires at least CA DB Read rights.
As it looks like, the function is using the ICertAdmin interface which requires one of the 3 privileged CA permission. Though enroll right would be enough when using ICertEnroll interface to retrieve CAExchange certificate.

**Comment by Crypt32** [comment]
Yes, you are correct. ICertAdmin requires admin priveleges. `CertificationAuthority.GetCAExchangeCertificate` must be rewritten to use `ICertRequest` interface.

**Comment by Crypt32** [comment]
This is fixed now and will be available in next build.

**Comment by StevenShockley** [comment]
Okay, I think this will get me part of the way there, but when I run Get-EnterprisePKIHealthStatus -CertificateAuthority <dnsname> it looks like it's doing 
```
$CA = 'PKI.CertificateServices.CertificateAuthority'
$CA.Ping()
```
and the Ping is failing because the user doesn't have rights to the service in Service Control Manager.  Changing the ACL on the service is more palatable than making the service account CA-local or enterprise admin though, so I'll try changing the ACL and let you know how it works.

Thanks!
