### ISSUE TITLE
Not possible to have private key in machine key store without installing

### ISSUE THREAD

**Issue by HQJaTu** [PKISolutions/PSPKI#64]
First: I have to admit, this is a corner case.

I need to get a X509Certificate2-object from PEM-file with `Convert-PemToPfx` to verify if it needs to be installed. If yes, I'll run `Set-ItemProperty` to actually install. However, since I'm not explicitly specifying install, the private key doesn't have `[Security.Cryptography.CspProviderFlags]::UseMachineKeyStore` which in my case is needed. The use case for the certificate is to use it with _NETWORK SERVICE_ -account. For that, I need to explicitly grant the private key access and it won't work, unless the private key is stored into machine key store.

For my use case to work, I'd either:
1) need `$install` to not install if cert already exists
or
2) need to be able to specify private key flags

Current logic will create the certificate and private key correctly, but will overwrite if doing `$install`. If not doing install, it is not possible to add key flags later.

**Comment by Crypt32** [comment]
I'm not sure if I understand the problem. You can specify store location (LocalMachine) when using `-Install` switch.

**Comment by HQJaTu** [comment]
The thing is: I cannot install without first checking if install is needed. I cannot overwrite existing, if existing certificate is valid and new-to-be-installed isn't. To get understanding what I'm about to install, first I need to do the conversion.

At the point where verfication is done and I already have a X509Certificate2-object, I can install that easily with a `Set-ItemProperty`-call. Since I chose **not** to install at PEM-conversion, the flags in the certificate are incorrect for _NETWORK SERVICE_ to even in theory have access.

My point is: Certificate flags cannot be changed after object construction. Setting the flags should be independent from installation operation.

**Comment by Crypt32** [comment]
> Setting the flags should be independent from installation operation.

you cannot change key location once the key is loaded. At this moment, you may need to run conversion twice: convert the certificate without installation flags to determine if certificate for service must be replaced. If there is a need, make second cmdlet call with installation parameters and store location.

**Comment by HQJaTu** [comment]
> you cannot change key location once the key is loaded
Yes. I learned that the hard way.

The thing (in my corner case) is, I know where I will install the certificate, if I choose to do so. In current version going directly for install is too destructive and having key flags depending on the install make approach tricky.

Given availability of source code, I tailored a version which doesn't do installs, but sets the flags as it would do if going for install.  This solves my problem.

Maybe I should work further with this and go for a generic version and publish it in a PR having new argument `prepareToInstall`.

**Comment by Crypt32** [comment]
> Given availability of source code, I tailored a version which doesn't do installs, but sets the flags as it would do if going for install. This solves my problem.

can you provide the code that works for you? I'm still not sure if I understand the problem.

**Comment by HQJaTu** [comment]
As I'm out of ideas how to rephrase, here goes:

```
function Convert-PemToPfx-2 {
[OutputType('[System.Security.Cryptography.X509Certificates.X509Certificate2]')]
[CmdletBinding()]
	param(
		[Parameter(Mandatory = $true, Position = 0)]
		[string]$InputPath,
		[string]$KeyPath,
		[string]$OutputPath,
		[Security.Cryptography.X509Certificates.X509KeySpecFlags]$KeySpec = "AT_KEYEXCHANGE",
		[string]$ProviderName = "Microsoft Enhanced RSA and AES Cryptographic Provider"
	)
	if ($PSBoundParameters.Verbose) {$VerbosePreference = "continue"}
	if ($PSBoundParameters.Debug) {
		$Host.PrivateData.DebugForegroundColor = "Cyan"
		$DebugPreference = "continue"
	}
	
	#region helper functions
	function __normalizeAsnInteger ($array) {
        $padding = $array.Length % 8
        if ($padding) {
            $array = $array[$padding..($array.Length - 1)]
        }
        [array]::Reverse($array)
        [Byte[]]$array
    }
	function __extractCert([string]$Text) {
		if ($Text -match "(?msx).*-{5}BEGIN\sCERTIFICATE-{5}(.+)-{5}END\sCERTIFICATE-{5}") {
		$keyFlags = [Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable
		#$keyFlags += [Security.Cryptography.X509Certificates.X509KeyStorageFlags]::MachineKeySet
		$RawData = [Convert]::FromBase64String($matches[1])
			try {
				New-Object Security.Cryptography.X509Certificates.X509Certificate2 -ArgumentList $RawData, "", $keyFlags
			} catch {throw "The data is not valid security certificate."}
			Write-Debug "X.509 certificate is correct."
		} else {throw "Missing certificate file."}
	}
	# returns [byte[]]
	function __composePRIVATEKEYBLOB($modulus, $PublicExponent, $PrivateExponent, $Prime1, $Prime2, $Exponent1, $Exponent2, $Coefficient) {
		Write-Debug "Calculating key length."
		$bitLen = "{0:X4}" -f $($modulus.Length * 8)
		Write-Debug "Key length is $($modulus.Length * 8) bits."
		[byte[]]$bitLen1 = Invoke-Expression 0x$([int]$bitLen.Substring(0,2))
		[byte[]]$bitLen2 = Invoke-Expression 0x$([int]$bitLen.Substring(2,2))
		[Byte[]]$PrivateKey = 0x07,0x02,0x00,0x00,0x00,0x24,0x00,0x00,0x52,0x53,0x41,0x32,0x00
		[Byte[]]$PrivateKey = $PrivateKey + $bitLen1 + $bitLen2 + $PublicExponent + ,0x00 + `
			$modulus + $Prime1 + $Prime2 + $Exponent1 + $Exponent2 + $Coefficient + $PrivateExponent
		$PrivateKey
	}
	# returns RSACryptoServiceProvider for dispose purposes
	function __attachPrivateKey($Cert, [Byte[]]$PrivateKey) {
		$cspParams = New-Object Security.Cryptography.CspParameters -Property @{
			ProviderName = $ProviderName
			KeyContainerName = "pspki-" + [Guid]::NewGuid().ToString()
			KeyNumber = [int]$KeySpec
		}
		$cspParams.Flags += [Security.Cryptography.CspProviderFlags]::UseMachineKeyStore
		$rsa = New-Object Security.Cryptography.RSACryptoServiceProvider $cspParams
		$rsa.ImportCspBlob($PrivateKey)
		$Cert.PrivateKey = $rsa
		$rsa
	}
	# returns Asn1Reader
	function __decodePkcs1($base64) {
		Write-Debug "Processing PKCS#1 RSA KEY module."
		$asn = New-Object SysadminsLV.Asn1Parser.Asn1Reader @(,[Convert]::FromBase64String($base64))
		if ($asn.Tag -ne 48) {throw "The data is invalid."}
		$asn
	}
	# returns Asn1Reader
	function __decodePkcs8($base64) {
		Write-Debug "Processing PKCS#8 Private Key module."
		$asn = New-Object SysadminsLV.Asn1Parser.Asn1Reader @(,[Convert]::FromBase64String($base64))
		if ($asn.Tag -ne 48) {throw "The data is invalid."}
		# version
		if (!$asn.MoveNext()) {throw "The data is invalid."}
		# algorithm identifier
		if (!$asn.MoveNext()) {throw "The data is invalid."}
		# octet string
		if (!$asn.MoveNextCurrentLevel()) {throw "The data is invalid."}
		if ($asn.Tag -ne 4) {throw "The data is invalid."}
		if (!$asn.MoveNext()) {throw "The data is invalid."}
		$asn
	}
	#endregion
	$ErrorActionPreference = "Stop"
	
	$File = Get-Item $InputPath -Force -ErrorAction Stop
	if ($KeyPath) {$Key = Get-Item $KeyPath -Force -ErrorAction Stop}
	
	# parse content
	$Text = Get-Content -Path $InputPath -Raw -ErrorAction Stop
	Write-Debug "Extracting certificate information..."
	$Cert = __extractCert $Text
	if ($Key) {$Text = Get-Content -Path $KeyPath -Raw -ErrorAction Stop}
	$asn = if ($Text -match "(?msx).*-{5}BEGIN\sPRIVATE\sKEY-{5}(.+)-{5}END\sPRIVATE\sKEY-{5}") {
		__decodePkcs8 $matches[1]
	} elseif ($Text -match "(?msx).*-{5}BEGIN\sRSA\sPRIVATE\sKEY-{5}(.+)-{5}END\sRSA\sPRIVATE\sKEY-{5}") {
		__decodePkcs1 $matches[1]
	}  else {throw "The data is invalid."}
	# private key version
	if (!$asn.MoveNext()) {throw "The data is invalid."}
	# modulus n
	if (!$asn.MoveNext()) {throw "The data is invalid."}
	$modulus = __normalizeAsnInteger $asn.GetPayload()
	Write-Debug "Modulus length: $($modulus.Length)"
	# public exponent e
	if (!$asn.MoveNext()) {throw "The data is invalid."}
	# public exponent must be 4 bytes exactly.
	$PublicExponent = if ($asn.GetPayload().Length -eq 3) {
		,0 + $asn.GetPayload()
	} else {
		$asn.GetPayload()
	}
	Write-Debug "PublicExponent length: $($PublicExponent.Length)"
	# private exponent d
	if (!$asn.MoveNext()) {throw "The data is invalid."}
	$PrivateExponent = __normalizeAsnInteger $asn.GetPayload()
	Write-Debug "PrivateExponent length: $($PrivateExponent.Length)"
	# prime1 p
	if (!$asn.MoveNext()) {throw "The data is invalid."}
	$Prime1 = __normalizeAsnInteger $asn.GetPayload()
	Write-Debug "Prime1 length: $($Prime1.Length)"
	# prime2 q
	if (!$asn.MoveNext()) {throw "The data is invalid."}
	$Prime2 = __normalizeAsnInteger $asn.GetPayload()
	Write-Debug "Prime2 length: $($Prime2.Length)"
	# exponent1 d mod (p-1)
	if (!$asn.MoveNext()) {throw "The data is invalid."}
	$Exponent1 = __normalizeAsnInteger $asn.GetPayload()
	Write-Debug "Exponent1 length: $($Exponent1.Length)"
	# exponent2 d mod (q-1)
	if (!$asn.MoveNext()) {throw "The data is invalid."}
	$Exponent2 = __normalizeAsnInteger $asn.GetPayload()
	Write-Debug "Exponent2 length: $($Exponent2.Length)"
	# coefficient (inverse of q) mod p
	if (!$asn.MoveNext()) {throw "The data is invalid."}
	$Coefficient = __normalizeAsnInteger $asn.GetPayload()
	Write-Debug "Coefficient length: $($Coefficient.Length)"
	# creating Private Key BLOB structure
	$PrivateKey = __composePRIVATEKEYBLOB $modulus $PublicExponent $PrivateExponent $Prime1 $Prime2 $Exponent1 $Exponent2 $Coefficient
	
	#region key attachment and export
	try {
		$rsaKey = __attachPrivateKey $Cert $PrivateKey
	} finally {
		if ($rsaKey -ne $null) {
			$rsaKey.Dispose()
			$Cert
		}
	}
}
```

**Comment by HQJaTu** [comment]
I fully understand the security precaution here. It's just the code does the trick for me. It doesn't install (as in overwrite existing certificate), but prepares the certificate to be installed later if so decided. Persisting the private key in the system is not a problem for me as it already is there, or will be after I choose to install the certificate.

As I mentioned multiple times: I need the private key to be accessible by NETWORK SERVICE -account. Not having the private key in machine store doesn't work for me.

That's why I suggested to separate installation operation and key storage flags as input parameters. Use cases vary. Sometimes not having the private key in machine store is needed for security. However, as I've proven, there are cases, where maximum security is not a criteria. Functioning application is.

**Comment by Crypt32** [comment]
I don't have solution for you right now. It is somewhat unusual case. If you found a solution to your case by editing the cmdlet -- I would suggest to use it as a workaround. I don't think it is wise to persist the key material on a system when the command was not asked to do (via -Install switch). The goal of this cmdlet is plain and simple: convert certificate and key files in PEM format and convert to PFX. Optional key installation (on prompt) is supported by a `-Install` switch.

**Comment by HQJaTu** [comment]
Yes, my solution is working for the particular application I needed to use this.

It's just that there will be next guy with another application. Having written few lines of code myself, I try to follow SOLID (https://en.wikipedia.org/wiki/SOLID). Separating flags from install-operation yields single responsibility. This results in a library that's fully generic, offering functionality for every single user. Having the currently implemented functionality as default makes total sense to 99,99% of the use cases. It's the 0.01% that do require the flags to be set independently of the install-action.

**Comment by Crypt32** [comment]
The `-Install` switch was requested multiple times in a common scenario: admins receive certificate and key file from management teams and they need to install the certificate in IIS. `Convert-PemToPfx` cmdlet was developed before `Import-PfxCertificate` built-in cmdlet shipped by Microsoft.

> It's just that there will be next guy with another application.

I review every use case module customers have and see if it makes a sense in a global picture. If it does, I implement it in my module. If not, I'm trying to supply a workaround. Your case is somewhat unusual to me and never had it in my practice. I'm leaving this as is until I get more requests.
