### ISSUE TITLE
Get-IssuedRequest CertificationAuthority Pipeline

### ISSUE THREAD

**Issue by snordog** [PKISolutions/PSPKI#80]
If you are using Get-CertificationAuthority and piping to Get-IssuedRequest, it only accepts one system name. In my environment I have two CA's, but it only passes the second value. 

```powershell
Get-CertificationAuthority | Get-IssuedRequest -Filter "Request.RequesterName -eq snordog"
```

The workaround I have been using is:

```powershell
Get-IssuedRequest -CertificationAuthority $(Get-CertificationAuthority) -Filter "Request.RequesterName -eq snordog"
```

**Comment by Crypt32** [comment]
Confirmed. Will work on it.
