### ISSUE TITLE
Unable to see extended attributes in Get-PendingRequest

### ISSUE THREAD

**Issue by jontowles** [PKISolutions/PSPKI#82]
I am trying to see the SAN in a pending request but there doesn't appear to be any way to do so. 

![image](https://user-images.githubusercontent.com/18011419/61089473-36a5b080-a409-11e9-9081-2ac0de53320c.png)

I currently add my SAN to certificate via extended properties. Essentially trying to use your powershell module to automatically approve or reject certs missing a SAN

**Comment by Crypt32** [comment]
if you know the ID of the request, you can make Extensions table lookup as follows:

``` PowerShell
$dbRow = $ca | Get-AdcsDatabaseRow -Table "Extension" -RowID $RequestID -Filter "ExtensionName -eq 2.5.29.17"
# check if $dbRow is not null
# do the rest
$bytes = [convert]::FromBase64String($dbRow.Properties["ExtensionRawValue"])
$asn = new-object system.security.cryptography.asnencodeddata "2.5.29.17",$bytes
$san = new-object system.security.cryptography.x509certificates.x509subjectalternativenamesextension $asn,$false
```
Where `$ca` is the CA object retrieved previously and `$RequestID` is request ID you retrieve from `Get-PendingRequest` command call.
