### ISSUE TITLE
Get-IssuedRequest -Filter property doesn't seem to support logical operators

### ISSUE THREAD

**Issue by mcdonamw** [PKISolutions/PSPKI#91]
I'm used to using logical operators in Filter properties for a number of cmdlets.  I assumed this was natively supported in all Powershell cmdlets, but it seems it does not work in pspki cmdlets, specifically Get-IssuedRequest.  

```
PS C:\>Get-IssuedRequest -CertificationAuthority myserver -Filter {RequestID -eq '852' -OR RequestID -eq '845'}

Specified column 'RequestID -eq '852' -OR RequestID' is not found.
At C:\Users\mmcdonald-a\Documents\WindowsPowerShell\Modules\PSPKI\3.4.2.0\Server\Get-RequestRow.ps1:29 char:17
+ ...               throw "Specified column '$($matches[1])' is not found."
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Specified colum...' is not found.:String) [], RuntimeException
    + FullyQualifiedErrorId : Specified column 'RequestID -eq '852' -OR RequestID' is not found. 
```

If I just pull all issued requests and pipe to Where-Object, it'll work with the logical operator but seems inefficient to pull all requests when I'm just looking for specific ones.

Figured I'd make an issue for this in case it wasn't intended to be this way by design.

**Comment by Crypt32** [comment]
`-Filter` parameter does not support logical operators by design. All filters are applied with `AND` operator implicitly. The syntax you are trying to execute is not valid for this command. Check cmdlet documentation for valid syntax examples: https://www.pkisolutions.com/tools/pspki/Get-IssuedRequest/. In fact, filters are strings that are parsed internally.

For given case (when request IDs are known in advance), you can use:
``` PowerShell
Get-IssuedRequest -CertificationAuthority myserver -RequestID 852, 845
```

**Comment by mcdonamw** [comment]
Thanks for your response.  I'm just curious, is there a specific reason for that choice?  I'm used to just about all other cmdlets I use that do support this natively, e.g. the AD cmdlets (Get-ADUser).  Logical operators are very useful when filtering.  The implicit AND is great and all but why limit it to just that?

**Comment by Crypt32** [comment]
> I'm just curious, is there a specific reason for that choice?

unerlying API limitation. Since they do not support logical operators, I can't do it either.

> How would you find issued certificates between a range?

something like this:

``` PowerShell
$from = (Get-Date).AddMoths(-12)
$to = (Get-Date).AddMonths(-6)
Get-IssuedReuqest -CA $ca -Filter "NotBefore -ge $from", "NotBefore -le $to"
```
This command will return requests that were issued in a range between 12 and 6 months ago.

**Comment by mcdonamw** [comment]
Ah gotcha.  Well if the underlying api can't support it then that's the easy answer!  Thanks for your help.
