### ISSUE TITLE
Error exporting CA templates to .dat

### ISSUE THREAD

**Issue by hmiller10** [PKISolutions/PSPKI#92]
Hello,

Using the following block of code I receive an error when attempting to export a certificate template that contains a / in the name like sha-2s/mime.

------
#Code Block

Function Export-CertificateTemplate {
<#
.Synopsis
    Exports certificate templates to a serialized format.
.Description
    Exports certificate templates to a serialized format. Exported templates can be distributed
    and imported in another forest.
.Parameter Template
    A collection of certificate templates to export. A collection can be retrieved by running
    Get-CertificateTemplate that is a part of PSPKI module: https://pspki.codeplex.com
.Parameter Path
    Specifies the path to export.
.Example
    $Templates = Get-CertificateTemplate -Name SmartCardV2, WebServerV3
    PS C:\> Export-CertificateTemplate $templates c:\temp\templates.dat
#>
[CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [PKI.CertificateTemplates.CertificateTemplate[]]$Template,
        [Parameter(Mandatory = $true)]
        [IO.FileInfo]$Path
    )
    if ($Template.Count -lt 1) {throw "At least one template must be specified in the 'Template' parameter."}
    $ErrorActionPreference = "Stop"

#region enums
    $HashAlgorithmGroup = 1
    $EncryptionAlgorithmGroup = 2
    $PublicKeyIdGroup = 3
    $SigningAlgorithmIdGroup = 4
    $RDNIdGroup = 5
    $ExtensionAttributeGroup = 6
    $EKUGroup = 7
    $CertificatePolicyGroup = 8
    $EnrollmentObjectGroup = 9
#endregion

#region funcs
    function Get-OIDid ($OID,$group) {
        $found = $false
        :outer for ($i = 0; $i -lt $oids.Count; $i++) {
            if ($script:oids[$i].Value -eq $OID.Value) {
                $ID = ++$i
                $found = $true
                break outer
            }
        }
        if (!$found) {
            $script:oids += New-Object psobject -Property @{
                Value = $OID.Value;
                Group = $group;
                Name = $OID.FriendlyName;
            }
            $ID = $script:oids.Count
        }
        $ID
    }
    function Get-Seconds ($str) {
        [void]("$str" -match "(\d+)\s(\w+)")
        $period = $matches[1] -as [int]
        $units = $matches[2]
        switch ($units) {
            "hours" {$period * 3600}
            "days" {$period * 3600 * 24}
            "weeks" {$period * 3600 * 168}
            "months" {$period * 3600 * 720}
            "years" {$period * 3600 * 8760}
        }
    }
#endregion

    $SB = New-Object Text.StringBuilder
    [void]$SB.Append(
@"
<GetPoliciesResponse xmlns="http://schemas.microsoft.com/windows/pki/2009/01/enrollmentpolicy">
    <response>
        <policyID/>
        <policyFriendlyName/>
        <nextUpdateHours>8</nextUpdateHours>
        <policiesNotChanged a:nil="true" xmlns:a="http://www.w3.org/2001/XMLSchema-instance"/>
        <policies>
"@)
    $script:oids = @()
    foreach ($temp in $Template) {
         [void]$SB.Append("<policy>")
        $OID = New-Object Security.Cryptography.Oid $temp.OID.Value, $temp.DisplayName
        $tempID = Get-OIDid $OID $EnrollmentObjectGroup
        # validity/renewal
        $validity = Get-Seconds $temp.Settings.ValidityPeriod
        $renewal = Get-Seconds $temp.Settings.RenewalPeriod
        # key usages
        $KU = if ([int]$temp.Settings.Cryptography.CNGKeyUsage -eq 0) {
            '<keyUsageProperty xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'
        } else {
            "<keyUsageProperty>$([int]$temp.Settings.CNGKeyUsage)</keyUsageProperty>"
        }
        # private key security
        $PKS = if ([string]::IsNullOrEmpty($temp.Settings.Cryptography.PrivateKeySecuritySDDL)) {
            '<permissions xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'
        } else {
            "<permissions>$($temp.Settings.PrivateKeySecuritySDDL)</permissions>"
        }
        # public key algorithm
        $KeyAlgorithm = if ($temp.Settings.Cryptography.KeyAlgorithm.Value -eq "1.2.840.113549.1.1.1") {
            '<algorithmOIDReference xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'
        } else {
            $kalgID = Get-OIDid $temp.Settings.Cryptography.KeyAlgorithm $PublicKeyIdGroup
            "<algorithmOIDReference>$kalgID</algorithmOIDReference>"
        }
        # superseded templates
        $superseded = if ($temp.Settings.SupersededTemplates.Length -eq 0) {
            '<supersededPolicies xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'    
        } else {
            $str = "<supersededPolicies>"
            $temp.Settings.SupersededTemplates | ForEach-Object {$str += "<commonName>$_</commonName>"}
            $str + "</supersededPolicies>"
        }
        # list of CSPs
        $CSPs = if ($temp.Settings.Cryptography.CSPList.Count -eq 0) {
            '<cryptoProviders xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'
        } else {
            $str = "<cryptoProviders>`n"
            $temp.Settings.Cryptography.CSPList | ForEach-Object {
                $str += "<provider>$_</provider>`n"
            }
            $str + "</cryptoProviders>"
        }
        # version
        [void]($temp.Version -match "(\d+)\.(\d+)")
        $major = $matches[1]
        $minor = $matches[2]
        # hash algorithm
        $hash = if ($temp.Settings.Cryptography.HashAlgorithm.Value -eq "1.3.14.3.2.26") {
            '<hashAlgorithmOIDReference xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'
        } else {
            $hashID = Get-OIDid $temp.Settings.Cryptography.HashAlgorithm $HashAlgorithmGroup
            "<hashAlgorithmOIDReference>$hashID</hashAlgorithmOIDReference>"
        }
        # enrollment agent
        $RAR = if ($temp.Settings.RegistrationAuthority.SignatureCount -eq 0) {
            '<rARequirements xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'
        } else {
            $str = @"
<rARequirements>
<rASignatures>$($temp.Settings.RegistrationAuthority.SignatureCount)</rASignatures>
"@
            if ([string]::IsNullOrEmpty($temp.Settings.RegistrationAuthority.ApplicationPolicy.Value)) {
                $str += '<rAEKUs xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'
            } else {
                $raapID = Get-OIDid $temp.Settings.RegistrationAuthority.ApplicationPolicy $EKUGroup
                $str += @"
<rAEKUs>
    <oIDReference>$raapID</oIDReference>
</rAEKUs>
"@
            }
            if ($temp.Settings.RegistrationAuthority.CertificatePolicies.Count -eq 0) {
                $str += '<rAPolicies xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'
            } else {
                $str += "                       <rAPolicies>"
                $temp.Settings.RegistrationAuthority.CertificatePolicies | ForEach-Object {
                    $raipID = Get-OIDid $_ $CertificatePolicyGroup
                    $str += "<oIDReference>$raipID</oIDReference>`n"
                }
                $str += "</rAPolicies>`n"
            }
            $str += "</rARequirements>`n"
            $str
        }
        # key archival
        $KAS = if (!$temp.Settings.KeyArchivalSettings.KeyArchival) {
            '<keyArchivalAttributes xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'
        } else {
            $kasID = Get-OIDid $temp.Settings.KeyArchivalSettings.EncryptionAlgorithm $EncryptionAlgorithmGroup
@"
<keyArchivalAttributes>
    <symmetricAlgorithmOIDReference>$kasID</symmetricAlgorithmOIDReference>
    <symmetricAlgorithmKeyLength>$($temp.Settings.KeyArchivalSettings.KeyLength)</symmetricAlgorithmKeyLength>
</keyArchivalAttributes>
"@
        }
        $sFlags = [Convert]::ToUInt32($("{0:x2}" -f [int]$temp.Settings.SubjectName),16)
        [void]$SB.Append(
@"
<policyOIDReference>$tempID</policyOIDReference>
<cAs>
    <cAReference>0</cAReference>
</cAs>
<attributes>
    <commonName>$($temp.Name)</commonName>
    <policySchema>$($temp.SchemaVersion)</policySchema>
    <certificateValidity>
        <validityPeriodSeconds>$validity</validityPeriodSeconds>
        <renewalPeriodSeconds>$renewal</renewalPeriodSeconds>
    </certificateValidity>
    <permission>
        <enroll>false</enroll>
        <autoEnroll>false</autoEnroll>
    </permission>
    <privateKeyAttributes>
        <minimalKeyLength>$($temp.Settings.Cryptography.MinimalKeyLength)</minimalKeyLength>
        <keySpec>$([int]$temp.Settings.Cryptography.KeySpec)</keySpec>
        $KU
        $PKS
        $KeyAlgorithm
        $CSPs
    </privateKeyAttributes>
    <revision>
        <majorRevision>$major</majorRevision>
        <minorRevision>$minor</minorRevision>
    </revision>
    $superseded
    <privateKeyFlags>$([int]$temp.Settings.Cryptography.PrivateKeyOptions)</privateKeyFlags>
    <subjectNameFlags>$sFlags</subjectNameFlags>
    <enrollmentFlags>$([int]$temp.Settings.EnrollmentOptions)</enrollmentFlags>
    <generalFlags>$([int]$temp.Settings.GeneralFlags)</generalFlags>
    $hash
    $rar
    $KAS
<extensions>
"@)
        foreach ($ext in $temp.Settings.Extensions) {
            $extID = Get-OIDid ($ext.Oid) $ExtensionAttributeGroup
            $critical = $ext.Critical.ToString().ToLower()
            $value = [Convert]::ToBase64String($ext.RawData)
            [void]$SB.Append("<extension><oIDReference>$extID</oIDReference><critical>$critical</critical><value>$value</value></extension>")
        }
        [void]$SB.Append("</extensions></attributes></policy>")
    }
    [void]$SB.Append("</policies></response>")
    [void]$SB.Append("<oIDs>")
    $n = 1
    $script:oids | ForEach-Object {
        [void]$SB.Append(@"
<oID>
    <value>$($_.Value)</value>
    <group>$($_.Group)</group>
    <oIDReferenceID>$n</oIDReferenceID>
    <defaultName>$($_.Name)</defaultName>
</oID>
"@)
        $n++
    }
    [void]$SB.Append("</oIDs></GetPoliciesResponse>")
    Set-Content -Path $Path -Value $SB.ToString() -Encoding Ascii
}#end function Export-CertificateTemplate

$Templates = Get-CertificateTemplate -Name * -ErrorAction Continue | Select-Object -Property Name

foreach ($Template in $Templates)
{
	$TemplateFile = ($Template).Name
    //if ($TemplateFile.Contains('/')) {$TemplateFile = $TemplateFile.ToString().Replace("/", "")}
    [PKI.CertificateTemplates.CertificateTemplate]$TemplateFile
	$Path = "{0}\{1}.{2}" -f "C:\Temp\Templates", $TemplateFile, "dat"
			
	Export-CertificateTemplate $TemplateFile $Path
}

------
Error Produced:

Set-Content : Could not find a part of the path 'C:\Temp\Templates\AUS\MIMEEncryptionandSigning.dat'.
At line:246 char:5
+     Set-Content -Path $Path -Value $SB.ToString() -Encoding Ascii
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Temp\Templat...nandSigning.dat:String) [Set-Content], DirectoryNotFoundException
    + FullyQualifiedErrorId : GetContentWriterDirectoryNotFoundError,Microsoft.PowerShell.Commands.SetContentCommand

------
The loop stops and will not export any additional templates.

If I attempt to replace the / with a space I get an error as well.

------
#Code Block

Function Export-CertificateTemplate {
<#
.Synopsis
    Exports certificate templates to a serialized format.
.Description
    Exports certificate templates to a serialized format. Exported templates can be distributed
    and imported in another forest.
.Parameter Template
    A collection of certificate templates to export. A collection can be retrieved by running
    Get-CertificateTemplate that is a part of PSPKI module: https://pspki.codeplex.com
.Parameter Path
    Specifies the path to export.
.Example
    $Templates = Get-CertificateTemplate -Name SmartCardV2, WebServerV3
    PS C:\> Export-CertificateTemplate $templates c:\temp\templates.dat
#>
[CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [PKI.CertificateTemplates.CertificateTemplate[]]$Template,
        [Parameter(Mandatory = $true)]
        [IO.FileInfo]$Path
    )
    if ($Template.Count -lt 1) {throw "At least one template must be specified in the 'Template' parameter."}
    $ErrorActionPreference = "Stop"

#region enums
    $HashAlgorithmGroup = 1
    $EncryptionAlgorithmGroup = 2
    $PublicKeyIdGroup = 3
    $SigningAlgorithmIdGroup = 4
    $RDNIdGroup = 5
    $ExtensionAttributeGroup = 6
    $EKUGroup = 7
    $CertificatePolicyGroup = 8
    $EnrollmentObjectGroup = 9
#endregion

#region funcs
    function Get-OIDid ($OID,$group) {
        $found = $false
        :outer for ($i = 0; $i -lt $oids.Count; $i++) {
            if ($script:oids[$i].Value -eq $OID.Value) {
                $ID = ++$i
                $found = $true
                break outer
            }
        }
        if (!$found) {
            $script:oids += New-Object psobject -Property @{
                Value = $OID.Value;
                Group = $group;
                Name = $OID.FriendlyName;
            }
            $ID = $script:oids.Count
        }
        $ID
    }
    function Get-Seconds ($str) {
        [void]("$str" -match "(\d+)\s(\w+)")
        $period = $matches[1] -as [int]
        $units = $matches[2]
        switch ($units) {
            "hours" {$period * 3600}
            "days" {$period * 3600 * 24}
            "weeks" {$period * 3600 * 168}
            "months" {$period * 3600 * 720}
            "years" {$period * 3600 * 8760}
        }
    }
#endregion

    $SB = New-Object Text.StringBuilder
    [void]$SB.Append(
@"
<GetPoliciesResponse xmlns="http://schemas.microsoft.com/windows/pki/2009/01/enrollmentpolicy">
    <response>
        <policyID/>
        <policyFriendlyName/>
        <nextUpdateHours>8</nextUpdateHours>
        <policiesNotChanged a:nil="true" xmlns:a="http://www.w3.org/2001/XMLSchema-instance"/>
        <policies>
"@)
    $script:oids = @()
    foreach ($temp in $Template) {
         [void]$SB.Append("<policy>")
        $OID = New-Object Security.Cryptography.Oid $temp.OID.Value, $temp.DisplayName
        $tempID = Get-OIDid $OID $EnrollmentObjectGroup
        # validity/renewal
        $validity = Get-Seconds $temp.Settings.ValidityPeriod
        $renewal = Get-Seconds $temp.Settings.RenewalPeriod
        # key usages
        $KU = if ([int]$temp.Settings.Cryptography.CNGKeyUsage -eq 0) {
            '<keyUsageProperty xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'
        } else {
            "<keyUsageProperty>$([int]$temp.Settings.CNGKeyUsage)</keyUsageProperty>"
        }
        # private key security
        $PKS = if ([string]::IsNullOrEmpty($temp.Settings.Cryptography.PrivateKeySecuritySDDL)) {
            '<permissions xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'
        } else {
            "<permissions>$($temp.Settings.PrivateKeySecuritySDDL)</permissions>"
        }
        # public key algorithm
        $KeyAlgorithm = if ($temp.Settings.Cryptography.KeyAlgorithm.Value -eq "1.2.840.113549.1.1.1") {
            '<algorithmOIDReference xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'
        } else {
            $kalgID = Get-OIDid $temp.Settings.Cryptography.KeyAlgorithm $PublicKeyIdGroup
            "<algorithmOIDReference>$kalgID</algorithmOIDReference>"
        }
        # superseded templates
        $superseded = if ($temp.Settings.SupersededTemplates.Length -eq 0) {
            '<supersededPolicies xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'    
        } else {
            $str = "<supersededPolicies>"
            $temp.Settings.SupersededTemplates | ForEach-Object {$str += "<commonName>$_</commonName>"}
            $str + "</supersededPolicies>"
        }
        # list of CSPs
        $CSPs = if ($temp.Settings.Cryptography.CSPList.Count -eq 0) {
            '<cryptoProviders xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'
        } else {
            $str = "<cryptoProviders>`n"
            $temp.Settings.Cryptography.CSPList | ForEach-Object {
                $str += "<provider>$_</provider>`n"
            }
            $str + "</cryptoProviders>"
        }
        # version
        [void]($temp.Version -match "(\d+)\.(\d+)")
        $major = $matches[1]
        $minor = $matches[2]
        # hash algorithm
        $hash = if ($temp.Settings.Cryptography.HashAlgorithm.Value -eq "1.3.14.3.2.26") {
            '<hashAlgorithmOIDReference xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'
        } else {
            $hashID = Get-OIDid $temp.Settings.Cryptography.HashAlgorithm $HashAlgorithmGroup
            "<hashAlgorithmOIDReference>$hashID</hashAlgorithmOIDReference>"
        }
        # enrollment agent
        $RAR = if ($temp.Settings.RegistrationAuthority.SignatureCount -eq 0) {
            '<rARequirements xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'
        } else {
            $str = @"
<rARequirements>
<rASignatures>$($temp.Settings.RegistrationAuthority.SignatureCount)</rASignatures>
"@
            if ([string]::IsNullOrEmpty($temp.Settings.RegistrationAuthority.ApplicationPolicy.Value)) {
                $str += '<rAEKUs xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'
            } else {
                $raapID = Get-OIDid $temp.Settings.RegistrationAuthority.ApplicationPolicy $EKUGroup
                $str += @"
<rAEKUs>
    <oIDReference>$raapID</oIDReference>
</rAEKUs>
"@
            }
            if ($temp.Settings.RegistrationAuthority.CertificatePolicies.Count -eq 0) {
                $str += '<rAPolicies xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'
            } else {
                $str += "                       <rAPolicies>"
                $temp.Settings.RegistrationAuthority.CertificatePolicies | ForEach-Object {
                    $raipID = Get-OIDid $_ $CertificatePolicyGroup
                    $str += "<oIDReference>$raipID</oIDReference>`n"
                }
                $str += "</rAPolicies>`n"
            }
            $str += "</rARequirements>`n"
            $str
        }
        # key archival
        $KAS = if (!$temp.Settings.KeyArchivalSettings.KeyArchival) {
            '<keyArchivalAttributes xmlns:a="http://www.w3.org/2001/XMLSchema-instance" a:nil="true"/>'
        } else {
            $kasID = Get-OIDid $temp.Settings.KeyArchivalSettings.EncryptionAlgorithm $EncryptionAlgorithmGroup
@"
<keyArchivalAttributes>
    <symmetricAlgorithmOIDReference>$kasID</symmetricAlgorithmOIDReference>
    <symmetricAlgorithmKeyLength>$($temp.Settings.KeyArchivalSettings.KeyLength)</symmetricAlgorithmKeyLength>
</keyArchivalAttributes>
"@
        }
        $sFlags = [Convert]::ToUInt32($("{0:x2}" -f [int]$temp.Settings.SubjectName),16)
        [void]$SB.Append(
@"
<policyOIDReference>$tempID</policyOIDReference>
<cAs>
    <cAReference>0</cAReference>
</cAs>
<attributes>
    <commonName>$($temp.Name)</commonName>
    <policySchema>$($temp.SchemaVersion)</policySchema>
    <certificateValidity>
        <validityPeriodSeconds>$validity</validityPeriodSeconds>
        <renewalPeriodSeconds>$renewal</renewalPeriodSeconds>
    </certificateValidity>
    <permission>
        <enroll>false</enroll>
        <autoEnroll>false</autoEnroll>
    </permission>
    <privateKeyAttributes>
        <minimalKeyLength>$($temp.Settings.Cryptography.MinimalKeyLength)</minimalKeyLength>
        <keySpec>$([int]$temp.Settings.Cryptography.KeySpec)</keySpec>
        $KU
        $PKS
        $KeyAlgorithm
        $CSPs
    </privateKeyAttributes>
    <revision>
        <majorRevision>$major</majorRevision>
        <minorRevision>$minor</minorRevision>
    </revision>
    $superseded
    <privateKeyFlags>$([int]$temp.Settings.Cryptography.PrivateKeyOptions)</privateKeyFlags>
    <subjectNameFlags>$sFlags</subjectNameFlags>
    <enrollmentFlags>$([int]$temp.Settings.EnrollmentOptions)</enrollmentFlags>
    <generalFlags>$([int]$temp.Settings.GeneralFlags)</generalFlags>
    $hash
    $rar
    $KAS
<extensions>
"@)
        foreach ($ext in $temp.Settings.Extensions) {
            $extID = Get-OIDid ($ext.Oid) $ExtensionAttributeGroup
            $critical = $ext.Critical.ToString().ToLower()
            $value = [Convert]::ToBase64String($ext.RawData)
            [void]$SB.Append("<extension><oIDReference>$extID</oIDReference><critical>$critical</critical><value>$value</value></extension>")
        }
        [void]$SB.Append("</extensions></attributes></policy>")
    }
    [void]$SB.Append("</policies></response>")
    [void]$SB.Append("<oIDs>")
    $n = 1
    $script:oids | ForEach-Object {
        [void]$SB.Append(@"
<oID>
    <value>$($_.Value)</value>
    <group>$($_.Group)</group>
    <oIDReferenceID>$n</oIDReferenceID>
    <defaultName>$($_.Name)</defaultName>
</oID>
"@)
        $n++
    }
    [void]$SB.Append("</oIDs></GetPoliciesResponse>")
    Set-Content -Path $Path -Value $SB.ToString() -Encoding Ascii
}#end function Export-CertificateTemplate

$Templates = Get-CertificateTemplate -Name * -ErrorAction Continue | Select-Object -Property Name

foreach ($Template in $Templates)
{
	$TemplateFile = ($Template).Name
    if ($TemplateFile.Contains('/')) {$TemplateFile = $TemplateFile.ToString().Replace("/", "")}
    [PKI.CertificateTemplates.CertificateTemplate]$TemplateFile
	$Path = "{0}\{1}.{2}" -f "C:\Temp\Templates", $TemplateFile, "dat"
			
	Export-CertificateTemplate $TemplateFile $Path
}

-----
Error Produced:

Export-CertificateTemplate : Cannot process argument transformation on parameter 'Template'. Cannot convert value "USS MIMESigningManual" to type 
"PKI.CertificateTemplates.CertificateTemplate[]". Error: "Cannot convert value "USS MIMESigningManual" to type 
"PKI.CertificateTemplates.CertificateTemplate". Error: "There is no such object on the server.
""
At line:10 char:29
+     Export-CertificateTemplate $TemplateFile $Path
+                                ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Export-CertificateTemplate], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Export-CertificateTemplate

How do I resolve this?

**Comment by Crypt32** [comment]
First error indicates that you specified wrong destination path. Second error indicates that invalid argument was specified in function call.

**Comment by hmiller10** [comment]
Vadims,

In the case of the first error here is how the destination path is defined. The initial backup folder is based on parameterized inputs from the person executing the script. The rest of the folders are derived as shown.

[Parameter(Mandatory = $true, HelpMessage = "Specify full path where CA backup should should reside. EG: E:\CABackups")]
	[alias("Folder")]
	[String]$BackupFolder

$TodaysFldr = "{0}\{1}" -f $BackupFolder, "CABackup_$(Get-ReportDate)"
$templateFldr = "{0}\{1}" -f $TodaysFldr, "Templates"
$Path = "{0}\{1}{2}" -f $templateFldr, $TemplateFile, ".dat"

In both cases the function does indeed export certificates to the .dat file format until it hits a template with a '/' in the name like S/MimeTemplate.

I really don't think the destination path is incorrect because the folders get created correctly and like I mentioned above the exports do occur for other templates that do not include a '/' in the name.

Any ideas as to what to do here?

As for the second error.

$Path = "{0}{1}.{2}" -f "C:\Temp\Templates", $TemplateFile, "dat"
Export-CertificateTemplate $TemplateFile $Path

Which argument is incorrect? The first is the template the second is the path to the .dat file? Where did I go wrong?

**Comment by Crypt32** [comment]
>  until it hits a template with a '/' in the name like S/MimeTemplate.

then you should update the script to change how destination file name is created by escaping disallowed characters. In this line:

``` PowerShell
if ($TemplateFile.Contains('/')) {$TemplateFile = $TemplateFile.ToString().Replace("/", "")}
```

**Comment by hmiller10** [comment]
Vadims,

Using the above 'if' statement, which I actually had already tried, I get this error now.

E:\scripts\Backup-CertAuthority-WIP.ps1 : Exception calling ".ctor" with "1" argument(s): "An invalid dn synta
been specified.
": At C:\Program Files\WindowsPowerShell\Modules\PSPKI\3.4.2.0\Server\Get-CertificateTemplate.ps1:67 char:48
+ ... ach-Object {New-Object PKI.CertificateTemplates.CertificateTemplate $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At line:1 char:1
+ .\Backup-CertAuthority-WIP.ps1 -BackupFolder 'E:\CABackupTest' -Thale ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Backup-CertAuthority-WIP.ps1

Any ideas what to try now.

**Comment by hmiller10** [comment]
After changing up the backup path information I am still only able to backup CA templates that do NOT have a '/' in the template name. 

Using this block of code: 
$BackupFolder = 'E:\CABackupTest'
$TodaysFldr = "{0}\{1}" -f $BackupFolder, "CABackup_$(Get-ReportDate)"
$TempBkpRoot = "{0}\{1}" -f $TodaysFldr, "Templates"

$Templates = Get-CertificateTemplate -Name * | Select-Object -Property *
foreach ($Template in $Templates)
{
	$TemplateFile = ($Template).Name
    if ($TemplateFile.Contains('/')) {$TemplateFile = $TemplateFile.ToString().Replace('/',"")}
	$Path = "{0}\{1}.{2}" -f $TempBkpRoot, $TemplateFile, "dat"
		
	Export-CertificateTemplate -Template $TemplateFile -Path $Path
}

I still get the following error (as an example)
Export-CertificateTemplate : Cannot process argument transformation on parameter 'Template'. Cannot convert value "USSMIMESigning" to type 
"PKI.CertificateTemplates.CertificateTemplate[]". Error: "Cannot convert value "USSMIMESigning" to type "PKI.CertificateTemplates.CertificateTemplate". 
Error: "There is no such object on the server.
""
At line:271 char:39
+     Export-CertificateTemplate -Template $TemplateFile -Path $Path
+                                          ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Export-CertificateTemplate], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Export-CertificateTemplate
 
Export-CertificateTemplate : Cannot process argument transformation on parameter 'Template'. Cannot convert value "USSMIMESigningManual" to type 
"PKI.CertificateTemplates.CertificateTemplate[]". Error: "Cannot convert value "USSMIMESigningManual" to type 
"PKI.CertificateTemplates.CertificateTemplate". Error: "There is no such object on the server.
""
At line:271 char:39
+     Export-CertificateTemplate -Template $TemplateFile -Path $Path
+                                          ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Export-CertificateTemplate], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Export-CertificateTemplate


Is this by design? Any thoughts on how to fix this now?
