### ISSUE TITLE
Cannot Connect to Remote CA

### ISSUE THREAD

**Issue by MRuth** [PKISolutions/PSPKI#93]
When attempting to connect to a remote Certificate Authority, the below error occurs:

`PS C:\WINDOWS\system32> Connect-CA -ComputerName '<CA Server FQDN>'`
`New-Object : Exception calling ".ctor" with "1" argument(s): "CCertConfig::GetField: The parameter is incorrect. 0x80070057 (WIN32: 87 ERROR_INVALID_PARAMETER)"`
`At C:\Program Files\WindowsPowerShell\Modules\PSPKI\3.4.1.0\Server\Connect-CertificationAuthority.ps1:13 char:4`
`+             New-Object PKI.CertificateServices.CertificateAuthority $ ...`
`+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException`
`    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand`

I also tried this on the newest version (3.4.2) and received the same results.

The workstation being used is not domain-joined, however the powershell instance is running with network-level credentials with an account that has CA Administrator capabilities.

I can access the CA remotely in the same powershell instance via ICertAdmin2 COM interfaces.

**Comment by Crypt32** [comment]
Can you provide StackTrace from exception? Run this line after exception is raised:
``` PowerShell
$errors[0].Exception.InnerException.StackTrace
```
and provide output here.

**Comment by MRuth** [comment]
```PowerShell
PS C:\WINDOWS\system32> Connect-CA -ComputerName '<CA Server FQDN>'
New-Object : Exception calling ".ctor" with "1" argument(s): "CCertConfig::GetField: The parameter is incorrect. 0x80070057 (WIN32: 87 ERROR_INVALID_PARAMETER)"
At C:\Program Files\WindowsPowerShell\Modules\PSPKI\3.4.2.0\Server\Connect-CertificationAuthority.ps1:13 char:4
+             New-Object PKI.CertificateServices.CertificateAuthority $ ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

PS C:\WINDOWS\system32> $Error[0].Exception.InnerException.StackTrace
   at CERTCLILib.CCertConfigClass.GetField(String strFieldName)
   at PKI.CertificateServices.CertificateAuthority.getInfoFromDs()
   at PKI.CertificateServices.CertificateAuthority.initialize()
   at PKI.CertificateServices.CertificateAuthority..ctor(String computerName)
```

Hope this helps!

**Comment by Crypt32** [comment]
This trace tells me that you ar running the code from AD envrionment (domain-joined computer). Is it correct?

**Comment by MRuth** [comment]
The code is being run on a non domain-joined computer.

I'm using the built-in **runas /netonly** functionality from the computer to allow the account to access the CA (as a network resource) under the context of a domain account with sufficient privileges to connect to and manage the CA.

What is the piece that determines if it is being run from a domain-joined machine?

**Comment by Crypt32** [comment]
The code diasagrees. For some reasons, the code reported that current computer is domain-joined. When you see this error, what this command returns:

``` PowerShell
[System.DirectoryServices.ActiveDirectory.Domain]::GetCurrentDomain().Name
```
also, what is the version of `SysadminsLV.PKI.dll` file in nodule's Library folder? When it was signed?

**Comment by MRuth** [comment]
The reported version of `SysadminsLV.PKI.dll` is 3.4.2.0 signed on 8/26/2019

Here's what I get when running the above command in the powershell process that is running under the network context of a domain user:
```PowerShell
PS C:\WINDOWS\system32> [System.DirectoryServices.ActiveDirectory.Domain]::GetCurrentDomain().Name
<FQDN of Domain>
```

I believe the process is able to get the current domain of the user's context, but the machine still isn't joined to the domain itself:

![image](https://user-images.githubusercontent.com/3927478/67834661-ffd9d000-fab5-11e9-9619-066ae9e55ac9.png)


If that code returns the domain name, what are the next steps that it takes to try and connect to the CA versus attempting to connect to the CA if the command doesn't return a domain?

Is there a way to supply the full config string `<Server FQDN>\<CA Name>` in the `Connect-CA` Cmdlet and have it connect over DCOM / ICertRequest / ICertAdmin directly?

**Comment by Crypt32** [comment]
Figured. It is a bug, because I used wrong method to determine if the machine is domain-joined. Actually, I'm checking user context instead of machine context. There is no workaround for now (unless you can modify DLL sources and recompile the library.

**Comment by Crypt32** [comment]
Bug details: https://github.com/PKISolutions/pkix.net/blob/deea9a796a0b1b3c1f7c5cdd798a741f75f863a6/PKI/Utils/DsUtils.cs#L124
`GetCurrentDomain()` must be replaced with `GetComputerDomain()`.

**Comment by Crypt32** [comment]
> Is there a way to supply the full config string <Server FQDN>\<CA Name> in the Connect-CA Cmdlet and have it connect over DCOM / ICertRequest / ICertAdmin directly?

yes, it is technically possible, but the code is still faulty, because all constructors go through buggy method.

**Comment by Crypt32** [comment]
Fix is available in vNext branch.

**Comment by MRuth** [comment]
Awesome, thank you!

I can confirm that the fix works and connections to the CA now work!
