### ISSUE TITLE
Can't connect to CA after 3.5 upgrade

### ISSUE THREAD

**Issue by Stan-Tastic** [PKISolutions/PSPKI#97]
Hi,
In my environment, PSPKI 3.4.1.0 worked fine, but after upgrading to 3.5 I can't get to CA anymore, for example:

```
Get-CertificationAuthority
Exception calling "EnumEnterpriseCAs" with "2" argument(s): "The server is not operational.
"
At C:\Program Files\WindowsPowerShell\Modules\PSPKI\3.5\Server\Get-CertificationAuthority.ps1:14 char:20
+ ... mputerSet" {[PKI.CertificateServices.CertificateAuthority]::EnumEnter ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : COMException
```

I can tell using Wireshark that the communication is happening, but aside that I'm not sure what's wrong.

**Comment by Crypt32** [comment]
Can you provide stack trace of the exception:
``` PowerShell
$error[0].Exception.InnerException.StackTrace
```

**Comment by Stan-Tastic** [comment]
> $error[0].Exception.InnerException.StackTrace
   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.PropertyCollection.Contains(String propertyName)
   at PKI.Utils.DsUtils.GetEntryProperty(String ldapPath, String prop)
   at PKI.CertificateServices.CertificateAuthority.getInfoFromDs()
   at PKI.CertificateServices.CertificateAuthority.initialize()
   at PKI.CertificateServices.CertificateAuthority.EnumEnterpriseCAs(String findType, String findValue)
   at CallSite.Target(Closure , CallSite , Type , String , String )

**Comment by Crypt32** [comment]
Is this CA server Enterprise or Standalone CA?

**Comment by Stan-Tastic** [comment]
There's a bunch of Enterprise CAs chained to a bunch of standalone CAs. I tested another command (Get-Certificate, I think) with an Enterprise CA, same result.

**Comment by Crypt32** [comment]
From what I can tell, the issue is caused by querying Active Directory. To be more specific, inability to connect to it. Can you, please, do more tests? Run the following command against different servers:
``` PowerShell
Connect-CA $CAHostName
```
when you find the server that fails, can you provide a bit more information about failing CA. Specifically, I need to know if it is Enterprise CA or Standalone CA and whether the computer with CA is joined to domain. Also, can you confirm that you are running command using domain account?

**Comment by Stan-Tastic** [comment]
I'm really not sure if we're on the same page...

The situation: pspki works as long as I use 3.4.1.0, when I upgrade to 3.5 it doesn't work anymore. Rollback to 3.4.1.0 = works, upgrade to 3.5 = doesn't work, I can do this all day and result stays the same.

3.5 is unable to connect to any of my Enterprise Subordinate CAs (currently I have 4 I can test with). 3.4.1.0 can connect to all of them. Yes, they are all domain-joined, and I'm running as domain user.

Let me know if you need any more info/debugging, I'm happy to help.

**Comment by Crypt32** [comment]
There was a change between 3.4.1 and 3.5 where I fixed issue with AD binding context. In the past, I contacted to AD of currently logged user. In fact, it was wrong behabior and I switched to contact to AD of current PC regardless of user membrship. This affects multi-domain scenarios.

Just one tiny check before we move further:

``` PowerShell
[system.directoryservices.activedirectory.domain]::getcurrentdomain()
[system.directoryservices.activedirectory.domain]::getcomputerdomain()
```
Do these commands return same domain or not?

**Comment by Stan-Tastic** [comment]
The output of both commands is 100% identical.

**Comment by tillo** [comment]
I am also available for testing, as I have the exact same issue (and command results) when using PSPKI 3.4.2 or 3.5 remotely.
We have a single domain for computers and users, and it makes no difference with which user I run the commands.
We also a single Enterprise SubCA, to which we are able to connect remotely with PSPKI 3.4.1.
We also have a single Enterprise RootCA, which is currently offline (I know it should be Standalone, but I'm guessing this is not what is causing the authentication issue).
Thank you for your help.

**Comment by Crypt32** [comment]
I tried to repro the issue, but failed. This simply works for me. I will try to add some debugging code and publish test DLL which will send extra information to console.

**Comment by Stan-Tastic** [comment]
I don't want to rush you (since 3.4.1.0 works fine for me), but were you able to prepare some instrumented DLL?

**Comment by Crypt32** [comment]
Attaching DLL file with some verbose information. Replace them in PSPKI module's Library folder.

[SysadminsLV.PKI.zip](https://github.com/PKISolutions/PSPKI/files/4716117/SysadminsLV.PKI.zip)


and show debug lines after calling `Get-CertificationAuthority` command.

**Comment by tillo** [comment]
Thank you for the verbose DLL version, it's really appreciated.
I haven't had time to use it yet, but I will soon and will report back the results.

**Comment by Crypt32** [comment]
Can you check PSPKI v3.7, which is released today and tell if issue is fixed or not.

**Comment by Stan-Tastic** [comment]
As far as I can tell, the issue is fixed now. Thank you!
