### ISSUE TITLE
OCSP returning malformed request after upgrade to 3.5

### ISSUE THREAD

**Issue by mfelicien** [PKISolutions/PSPKI#98]
Upgrading from version  3.4.1.0 ocsp fails to work with malformed request

$Cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2
$Cert.Import("C:\Templar\certificate.crt")
$request = New-Object pki.ocsp.ocsprequest $cert
$Response = $Request.SendRequest()
$response 

 Version                  : 0
ResponseType             : id_pkix_ocsp_basic
**ResponseStatus           : MalformedRequest**
ProducedAt               : 1/1/0001 12:00:00 AM
NonceReceived            : False
NonceValue               : 
ResponderKeyId           : 
ResponderNameId          : 
Request                  : PKI.OCSP.OCSPRequest
SignerCertificates       : 
Responses                : 
ResponseExtensions       : 
HttpHeaders              : {Content-Length, Cache-Control, Content-Type, Date...}
SignerCertificateIsValid : False
SignatureIsValid         : False
ChainErrorInformation    : 
ResponseErrorInformation : None
SignatureAlgorithm       : 
RawData                  : {48, 3, 10, 1...}

**Comment by Crypt32** [comment]
Can you try this approach:
```
$Response = $Request.SendRequest("POST")
```
And confirm if it does work.

**Comment by mfelicien** [comment]
Oh, well that was easy :) . Thanks that did work

**Comment by Crypt32** [comment]
There is a bug associated with double URL encoding. I've fixed this in internal build.

**Comment by Crypt32** [comment]
Updated in v3.7.2: https://www.powershellgallery.com/packages/PSPKI/3.7.2
