### ISSUE TITLE
new-selfsignedcertificateex : Exception calling "Build" with "1" argument(s): "Cannot find the certificate and private key for decryption."

### ISSUE THREAD

**Issue by jmeerdink** [PKISolutions/PSPKI#99]
Tried on Win 10 / Server 2016, all with PS5.1

I’m retrieving our in-house CA cert with

$sc = get-item Cert:\CurrentUser\ca\8CD9F4687EACECE660B6D7F5919EBC436FE433B9

But when I attempt to use that signing cert with a new cert request as 

new-selfsignedcertificateex -keyspec Signature -subject "cn=mach01.domain.com" -EnhancedKeyUsage "Server Authentication","Client Authentication" -KeyLength 2048 -issuer $sc

this error pops:
new-selfsignedcertificateex : Exception calling "Build" with "1" argument(s): "Cannot find the certificate and private key for decryption.

It seems that the private key from the signing cert isn’t available. I’m not sure if that’s a problem with our signing cert or just the way I’m trying to use it.

**Comment by Crypt32** [comment]
Does your certificate has associated private key? Say, when you open the certificate in Certifificates MMC, do you see that private key is there?

**Comment by jmeerdink** [comment]
If I look at the Details pane on the signing cert, I don’t see a private key. Is that where I should see it?

Jay Meerdink
Database Administrator IV
ConServe
An ACA International PPMS Certified Agency
A Business Ethics Award Recipient
P: (585) 421-1000 ext. 3205
F: (585) 421-1028

**Comment by Crypt32** [comment]
It is on General tab, at the bottom. You should see something like this:
![image](https://user-images.githubusercontent.com/6384119/78702086-b61ccd80-7910-11ea-9a01-1c587e601028.png)

**Comment by jmeerdink** [comment]
No – that message isn’t on that cert.

Jay Meerdink
Database Administrator IV
ConServe
An ACA International PPMS Certified Agency
A Business Ethics Award Recipient
P: (585) 421-1000 ext. 3205
F: (585) 421-1028

**Comment by Crypt32** [comment]
Then you cannot use this certificate to sign other certificates, because signing requires private key.

**Comment by jmeerdink** [comment]
OK – I was confused between validating the cert through the chain, and using the cert to sign.

Thank you!

Jay Meerdink
Database Administrator IV
ConServe
An ACA International PPMS Certified Agency
A Business Ethics Award Recipient
P: (585) 421-1000 ext. 3205
F: (585) 421-1028

**Comment by Crypt32** [comment]
yes, these are two different and almost unrelated things.
